### ISSUE TITLE
[BUG] MultiColumnPKDataTypeSuite07 fails with tidb-v2.0.11

### ISSUE THREAD

**Issue by marsishandsome** [pingcap/tispark#1000]
**Describe the bug**

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tispark_regression_test_daily/detail/tispark_regression_test_daily/35/pipeline/103

```
- Default value information not fetched

MultiColumnPKDataTypeSuite07:

org.apache.spark.sql.types.pk.MultiColumnPKDataTypeSuite07 *** ABORTED ***

  java.lang.RuntimeException: Unable to load a Suite class that was discovered in the runpath: org.apache.spark.sql.types.pk.MultiColumnPKDataTypeSuite07

  at org.scalatest.tools.DiscoverySuite$.getSuiteInstance(DiscoverySuite.scala:81)

  at org.scalatest.tools.DiscoverySuite$$anonfun$1.apply(DiscoverySuite.scala:38)

  at org.scalatest.tools.DiscoverySuite$$anonfun$1.apply(DiscoverySuite.scala:37)

  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)

  at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)

  at scala.collection.Iterator$class.foreach(Iterator.scala:891)

  at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)

  at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)

  at scala.collection.AbstractIterable.foreach(Iterable.scala:54)

  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)

  ...

  Cause: com.mysql.jdbc.MysqlDataTruncation: Data truncation: invalid time format: '{1969 12 31 17 0 1 0}'

  at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3971)

  at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)

  at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)

  at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)

  at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2483)

  at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2441)

  at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:845)

  at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:745)

  at org.apache.spark.sql.test.SharedSQLContext$.loadSQLFile(SharedSQLContext.scala:257)

  at org.apache.spark.sql.test.SharedSQLContext$class.loadSQLFile(SharedSQLContext.scala:84)
```

**Comment by birdstorm** [comment]
Seems to be a bug in TiDB v2.0.11, I raised an issue in their repository.

https://github.com/pingcap/tidb/issues/11727
