### ISSUE TITLE
[BUG] java.lang.NoClassDefFoundError: Could not initialize class com.pingcap.tispark.utils.ReflectionUtil$

### ISSUE THREAD

**Issue by zoeminghong** [pingcap/tispark#1006]
**Describe the bug**

我按照官网的教程（[https://pingcap.com/docs-cn/v3.0/reference/tispark/](https://pingcap.com/docs-cn/v3.0/reference/tispark/)），进行相应的尝试，通过 spark-sql 命令方式进行验证的时候，发生了如下的错误信息
![image](https://user-images.githubusercontent.com/10401743/62760560-dc0a7d80-bab6-11e9-9595-b2589b7c574d.png)

spark version: 2.3.1
tispark version: tispark-core-2.1.2-spark_2.3-jar-with-dependencies.jar

**Comment by marsishandsome** [comment]
请问是否把`tispark-core-2.1.2-spark_2.3-jar-with-dependencies.jar`拷贝到了${SPARK_HOME}/jars/下面？

如果是standalone集群的话，需要拷贝到所有worker节点，并且重启集群

**Comment by marsishandsome** [comment]
能否把截图截全，我看不到行号

**Comment by marsishandsome** [comment]
请问一下你是local模式还是standalone模式？tispark jar包是放到${SPARK_HOME}/jars目录还是通过spark-submit --jars传递的？

**Comment by zoeminghong** [comment]
@marsishandsome 你好，我是spark cluster模式，tispark jar 已经放在各个spark集群节点相应的位置上，`spark.sql(use test)` 这一步行为操作是没有异常的

**Comment by marsishandsome** [comment]
老的tispark包有没有删除？spark集群有没有重启？

**Comment by zoeminghong** [comment]
不存在老的tispark，我是第一次尝试，spark集群重启过的，因为不是要添加两个配置项吗，哦对了我用的是hdp的集群

**Comment by marsishandsome** [comment]
能否试一下把spark成换官方的版本 https://archive.apache.org/dist/spark/spark-2.3.1/

**Comment by marsishandsome** [comment]
官方的spark-2.3.1和spark-2.3.2有api不兼容的地方，tispark为了解决这个不兼容做了一些特殊操作，我猜测可能是hdp的2.3.1和官方的不太一样导致

**Comment by zoeminghong** [comment]
好的，我尝试一下

**Comment by marsishandsome** [comment]
请参考这行代码 

https://github.com/pingcap/tispark/blob/0586fa6b23f6d5530fd298dd764d83dbb43f8752/core/src/main/scala/com/pingcap/tispark/utils/ReflectionUtil.scala#L64

**Comment by zoeminghong** [comment]
@marsishandsome 我已经尝试使用社区版 spark 相同版本情况下，是没有问题的，demo 通过了，你们 HDP 版本没有做相应的适配吗？

**Comment by birdstorm** [comment]
@zoeminghong 我们会检查一下各 spark 版本的兼容性。目前没有特地为 HDP 版本适配。

**Comment by zoeminghong** [comment]
@birdstorm 好的，希望可以尽快，其实我觉得很多公司大数据使用 HDP/CDH 平台，小公司一般更加倾向于资源的共用。

**Comment by marsishandsome** [comment]
@zoeminghong 我们会尽快支持

**Comment by zoeminghong** [comment]
@marsishandsome 目前没有计划，相应的 HDP 最新的版本还没有更新

**Comment by marsishandsome** [comment]
好的，那我们支持一下，预计下周发布tispark-2.1.3，到时会把这个问题的修复一起发布

**Comment by marsishandsome** [comment]
@zoeminghong PR已经提了https://github.com/pingcap/tispark/pull/1017

**Comment by marsishandsome** [comment]
@zoeminghong tispark-2.1.3已经发布了，里面包含了这个问题的修复，请到这个页面进行下载  https://github.com/pingcap/tispark/releases/tag/v2.1.3

**Comment by zoeminghong** [comment]
@marsishandsome 太棒了，感谢

**Comment by zoeminghong** [comment]
@marsishandsome 我使用最新的进行了尝试，还是不行，错误如下

```
scala> spark.sql("use test")
res2: org.apache.spark.sql.DataFrame = []

scala> spark.sql("select count(*) from gejx").show
19/08/16 14:43:13 WARN KVErrorHandler: NotLeader Error with region id 40 and store id 4, new store id 6
19/08/16 14:43:13 WARN KVErrorHandler: Failed to send notification back to driver since CacheInvalidateCallBack is null in executor node.
org.apache.spark.sql.catalyst.errors.package$TreeNodeException: execute, tree:
Exchange SinglePartition
+- *(1) HashAggregate(keys=[], functions=[partial_specialsum(count(1)#22L, LongType, 0)], output=[rewriteSum#24L])
   +- TiSpark CoprocessorRDD{[table: gejx] TableScan, KeyRange: ([t\200\000\000\000\000\000\000+_r\000\000\000\000\000\000\000\000], [t\200\000\000\000\000\000\000+_s\000\000\000\000\000\000\000\000]), Aggregates: Count(1), startTs: 410501197008994305}

  at org.apache.spark.sql.catalyst.errors.package$.attachTree(package.scala:56)
  at org.apache.spark.sql.execution.exchange.ShuffleExchangeExec.doExecute(ShuffleExchangeExec.scala:119)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
  at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
  at org.apache.spark.sql.execution.InputAdapter.inputRDDs(WholeStageCodegenExec.scala:371)
  at org.apache.spark.sql.execution.aggregate.HashAggregateExec.inputRDDs(HashAggregateExec.scala:150)
  at org.apache.spark.sql.execution.WholeStageCodegenExec.doExecute(WholeStageCodegenExec.scala:605)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
  at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
  at org.apache.spark.sql.execution.SparkPlan.getByteArrayRdd(SparkPlan.scala:247)
  at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:337)
  at org.apache.spark.sql.execution.CollectLimitExec.executeCollect(limit.scala:38)
  at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$collectFromPlan(Dataset.scala:3273)
  at org.apache.spark.sql.Dataset$$anonfun$head$1.apply(Dataset.scala:2484)
  at org.apache.spark.sql.Dataset$$anonfun$head$1.apply(Dataset.scala:2484)
  at org.apache.spark.sql.Dataset$$anonfun$52.apply(Dataset.scala:3254)
  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:77)
  at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3253)
  at org.apache.spark.sql.Dataset.head(Dataset.scala:2484)
  at org.apache.spark.sql.Dataset.take(Dataset.scala:2698)
  at org.apache.spark.sql.Dataset.showString(Dataset.scala:254)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:723)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:682)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:691)
  ... 49 elided
Caused by: java.lang.IllegalArgumentException: wrong number of arguments
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at com.pingcap.tispark.utils.ReflectionUtil$ReflectionMapPartitionWithIndexInternal.invoke(ReflectionUtil.scala:117)
  at org.apache.spark.sql.execution.CoprocessorRDD$$anonfun$doExecute$1.apply(CoprocessorRDD.scala:82)
  at org.apache.spark.sql.execution.CoprocessorRDD$$anonfun$doExecute$1.apply(CoprocessorRDD.scala:78)
  at scala.collection.immutable.List.map(List.scala:273)
  at org.apache.spark.sql.execution.CoprocessorRDD.doExecute(CoprocessorRDD.scala:77)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
  at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
  at org.apache.spark.sql.execution.InputAdapter.inputRDDs(WholeStageCodegenExec.scala:371)
  at org.apache.spark.sql.execution.aggregate.HashAggregateExec.inputRDDs(HashAggregateExec.scala:150)
  at org.apache.spark.sql.execution.WholeStageCodegenExec.doExecute(WholeStageCodegenExec.scala:605)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
  at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
  at org.apache.spark.sql.execution.exchange.ShuffleExchangeExec.prepareShuffleDependency(ShuffleExchangeExec.scala:92)
  at org.apache.spark.sql.execution.exchange.ShuffleExchangeExec$$anonfun$doExecute$1.apply(ShuffleExchangeExec.scala:128)
  at org.apache.spark.sql.execution.exchange.ShuffleExchangeExec$$anonfun$doExecute$1.apply(ShuffleExchangeExec.scala:119)
  at org.apache.spark.sql.catalyst.errors.package$.attachTree(package.scala:52)
  ... 80 more
```

**Comment by marsishandsome** [comment]
@zoeminghong 我email给你了一个jar包，麻烦在你本地测试一下，多谢

**Comment by marsishandsome** [comment]
经过测试，新的jar包可以正常运行
