### ISSUE TITLE
[BUG] Distinct without alias throws NullPointerException

### ISSUE THREAD

**Issue by birdstorm** [pingcap/tispark#1039]
**Describe the bug**

Distinct without alias fails.

**What did you do**

```
create table t(c1 int);
insert into t values (2), (3);
select distinct(c1), 1 as w from t;
select distinct(c1) as d, 1 as w from t;
```

**What do you expect**

Both select should be ok.

**What happens instead**

First select fails while the second one succeeds.
```
ERROR Executor: Exception in task 0.0 in stage 1.0 (TID 1)
java.lang.NullPointerException: at index 2
	at com.google.common.collect.ObjectArrays.checkElementNotNull(ObjectArrays.java:225)
	at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:215)
	at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:209)
	at com.google.common.collect.ImmutableList.construct(ImmutableList.java:327)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:244)
	at com.pingcap.tikv.operation.transformer.RowTransformer.<init>(RowTransformer.java:86)
	at com.pingcap.tikv.operation.transformer.RowTransformer.<init>(RowTransformer.java:41)
	at com.pingcap.tikv.operation.transformer.RowTransformer$Builder.build(RowTransformer.java:52)
	at com.pingcap.tikv.operation.SchemaInfer.buildTransform(SchemaInfer.java:83)
	at com.pingcap.tikv.operation.SchemaInfer.<init>(SchemaInfer.java:53)
	at com.pingcap.tikv.operation.SchemaInfer.create(SchemaInfer.java:46)
	at com.pingcap.tikv.operation.SchemaInfer.create(SchemaInfer.java:42)
	at com.pingcap.tikv.operation.iterator.CoprocessIterator.getRowIterator(CoprocessIterator.java:78)
	at com.pingcap.tikv.Snapshot.tableRead(Snapshot.java:97)
	at org.apache.spark.sql.tispark.TiRowRDD$$anon$1.<init>(TiRowRDD.scala:69)
	at org.apache.spark.sql.tispark.TiRowRDD.compute(TiRowRDD.scala:59)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
19/08/16 19:15:42 WARN TaskSetManager: Lost task 0.0 in stage 1.0 (TID 1, localhost, executor driver): java.lang.NullPointerException: at index 2
	at com.google.common.collect.ObjectArrays.checkElementNotNull(ObjectArrays.java:225)
	at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:215)
	at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:209)
	at com.google.common.collect.ImmutableList.construct(ImmutableList.java:327)
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:244)
	at com.pingcap.tikv.operation.transformer.RowTransformer.<init>(RowTransformer.java:86)
	at com.pingcap.tikv.operation.transformer.RowTransformer.<init>(RowTransformer.java:41)
	at com.pingcap.tikv.operation.transformer.RowTransformer$Builder.build(RowTransformer.java:52)
	at com.pingcap.tikv.operation.SchemaInfer.buildTransform(SchemaInfer.java:83)
	at com.pingcap.tikv.operation.SchemaInfer.<init>(SchemaInfer.java:53)
	at com.pingcap.tikv.operation.SchemaInfer.create(SchemaInfer.java:46)
	at com.pingcap.tikv.operation.SchemaInfer.create(SchemaInfer.java:42)
	at com.pingcap.tikv.operation.iterator.CoprocessIterator.getRowIterator(CoprocessIterator.java:78)
	at com.pingcap.tikv.Snapshot.tableRead(Snapshot.java:97)
	at org.apache.spark.sql.tispark.TiRowRDD$$anon$1.<init>(TiRowRDD.scala:69)
	at org.apache.spark.sql.tispark.TiRowRDD.compute(TiRowRDD.scala:59)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:49)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Spark and TiSpark version info**
Spark: v2.4.3
TiSpark: master

**Comment by birdstorm** [comment]
Temporary fix by #1054

**Comment by marsishandsome** [comment]
TODO: support pushdown aggregate with alias

**Comment by shiyuhang0** [comment]
closed this and open a new feature-request
