### ISSUE TITLE
[BUG] DataTypePKSuite failed because of assertion failed

### ISSUE THREAD

**Issue by marsishandsome** [pingcap/tispark#1047]
**Describe the bug**
https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tispark_regression_test_daily/runs/47/nodes/1418/steps/1732/log/?start=0

```
INFO SharedSQLContext: generate data is enabled and seed is 1566243556784
```

```
org.apache.spark.sql.types.pk.DataTypePKSuite *** ABORTED ***
[2019-08-19T19:43:10.452Z]   java.lang.RuntimeException: Unable to load a Suite class that was discovered in the runpath: org.apache.spark.sql.types.pk.DataTypePKSuite
[2019-08-19T19:43:10.452Z]   at org.scalatest.tools.DiscoverySuite$.getSuiteInstance(DiscoverySuite.scala:81)
[2019-08-19T19:43:10.452Z]   at org.scalatest.tools.DiscoverySuite$$anonfun$1.apply(DiscoverySuite.scala:38)
[2019-08-19T19:43:10.452Z]   at org.scalatest.tools.DiscoverySuite$$anonfun$1.apply(DiscoverySuite.scala:37)
[2019-08-19T19:43:10.452Z]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[2019-08-19T19:43:10.452Z]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[2019-08-19T19:43:10.452Z]   at scala.collection.Iterator$class.foreach(Iterator.scala:891)
[2019-08-19T19:43:10.452Z]   at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
[2019-08-19T19:43:10.452Z]   at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[2019-08-19T19:43:10.452Z]   at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[2019-08-19T19:43:10.452Z]   at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
[2019-08-19T19:43:10.452Z]   ...
[2019-08-19T19:43:10.452Z]   Cause: java.lang.AssertionError: assertion failed: Generated random values(50) is less than needed(51).
[2019-08-19T19:43:10.452Z]   at scala.Predef$.assert(Predef.scala:170)
[2019-08-19T19:43:10.452Z]   at org.apache.spark.sql.test.generator.ColumnValueGenerator.next(ColumnValueGenerator.scala:281)
[2019-08-19T19:43:10.452Z]   at org.apache.spark.sql.test.generator.ColumnValueGenerator.next(ColumnValueGenerator.scala:269)
[2019-08-19T19:43:10.452Z]   at org.apache.spark.sql.test.generator.TestDataGenerator$.org$apache$spark$sql$test$generator$TestDataGenerator$$generateRandomColValue(TestDataGenerator.scala:277)
[2019-08-19T19:43:10.452Z]   at org.apache.spark.sql.test.generator.TestDataGenerator$$anonfun$org$apache$spark$sql$test$generator$TestDataGenerator$$generateRandomRow$1.apply$mcVI$sp(TestDataGenerator.scala:322)
[2019-08-19T19:43:10.452Z]   at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
[2019-08-19T19:43:10.452Z]   at org.apache.spark.sql.test.generator.TestDataGenerator$.org$apache$spark$sql$test$generator$TestDataGenerator$$generateRandomRow(TestDataGenerator.scala:319)
[2019-08-19T19:43:10.452Z]   at org.apache.spark.sql.test.generator.TestDataGenerator$$anonfun$generateRandomRows$2.apply(TestDataGenerator.scala:355)
[2019-08-19T19:43:10.452Z]   at org.apache.spark.sql.test.generator.TestDataGenerator$$anonfun$generateRandomRows$2.apply(TestDataGenerator.scala:354)
[2019-08-19T19:43:10.452Z]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
```

**Comment by marsishandsome** [comment]
https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tispark_regression_test_daily/runs/54/nodes/738/steps/1001/log/?start=0
