### ISSUE TITLE
[BUG] ci failed: test show databases/tables

### ISSUE THREAD

**Issue by marsishandsome** [pingcap/tispark#1056]
https://internal.pingcap.net/idc-jenkins/blue/rest/organizations/jenkins/pipelines/tispark_regression_test_daily/runs/50/nodes/731/steps/974/log/?start=0

```
[2019-08-21T19:09:08.172Z] - test show databases/tables *** FAILED ***
[2019-08-21T19:09:08.172Z]   java.lang.UnsupportedOperationException:
[2019-08-21T19:09:08.172Z]   at com.google.common.collect.UnmodifiableIterator.remove(UnmodifiableIterator.java:46)
[2019-08-21T19:09:08.172Z]   at java.util.Collection.removeIf(Collection.java:415)
[2019-08-21T19:09:08.172Z]   at com.pingcap.tikv.catalog.Catalog$CatalogCache.listTables(Catalog.java:89)
[2019-08-21T19:09:08.172Z]   at com.pingcap.tikv.catalog.Catalog.listTables(Catalog.java:185)
[2019-08-21T19:09:08.172Z]   at com.pingcap.tispark.MetaManager.getTables(MetaManager.scala:36)
[2019-08-21T19:09:08.172Z]   at org.apache.spark.sql.catalyst.catalog.TiDirectExternalCatalog.listTables(TiDirectExternalCatalog.scala:56)
[2019-08-21T19:09:08.172Z]   at org.apache.spark.sql.catalyst.catalog.TiDirectExternalCatalog.listTables(TiDirectExternalCatalog.scala:60)
[2019-08-21T19:09:08.172Z]   at org.apache.spark.sql.catalyst.catalog.SessionCatalog.listTables(SessionCatalog.scala:765)
[2019-08-21T19:09:08.172Z]   at org.apache.spark.sql.catalyst.catalog.TiCompositeSessionCatalog.listTables(TiCompositeSessionCatalog.scala:219)
[2019-08-21T19:09:08.172Z]   at org.apache.spark.sql.catalyst.catalog.TiCompositeSessionCatalog.listTables(TiCompositeSessionCatalog.scala:204)
```

**Comment by zhexuany** [comment]
It seems we have concurrent access issue here.

**Comment by zhexuany** [comment]
After some investigation, it is not a concurrent issue. The unsupported operation exception was thrown because of the implementation of remove of `UnmodifiableIterator`
