### ISSUE TITLE
[BUG] No Matching column

### ISSUE THREAD

**Issue by marsishandsome** [pingcap/tispark#1161]
```
CREATE TABLE `t_no_match_column` (
  `json` text DEFAULT NULL
)
```

```
select temp44.id from (
    SELECT get_json_object(t.json,  '$.id') as id from t_no_match_column t
) as temp44 order by temp44.id desc limit 1
```

```
No Matching column id from table t_no_match_column
com.pingcap.tikv.exception.TiExpressionException: No Matching column id from table t_no_match_column
	at com.pingcap.tikv.expression.ColumnRef.resolve(ColumnRef.java:71)
	at com.pingcap.tikv.expression.visitor.MetaResolver.visit(MetaResolver.java:52)
	at com.pingcap.tikv.expression.visitor.MetaResolver.visit(MetaResolver.java:24)
	at com.pingcap.tikv.expression.ColumnRef.accept(ColumnRef.java:141)
	at com.pingcap.tikv.expression.visitor.MetaResolver.lambda$resolve$0(MetaResolver.java:42)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.pingcap.tikv.expression.visitor.MetaResolver.resolve(MetaResolver.java:42)
	at com.pingcap.tikv.meta.TiDAGRequest.resolve(TiDAGRequest.java:264)
	at org.apache.spark.sql.TiStrategy.toCoprocessorRDD(TiStrategy.scala:159)
	at org.apache.spark.sql.TiStrategy.pruneFilterProject(TiStrategy.scala:416)
	at org.apache.spark.sql.TiStrategy.pruneTopNFilterProject(TiStrategy.scala:312)
	at org.apache.spark.sql.TiStrategy.takeOrderedAndProject(TiStrategy.scala:351)
	at org.apache.spark.sql.TiStrategy.org$apache$spark$sql$TiStrategy$$doPlan(TiStrategy.scala:521)
	at org.apache.spark.sql.TiStrategy$$anonfun$apply$1.applyOrElse(TiStrategy.scala:146)
	at org.apache.spark.sql.TiStrategy$$anonfun$apply$1.applyOrElse(TiStrategy.scala:144)
```

**Comment by birdstorm** [comment]
Closed in #1163
