### ISSUE TITLE
[BUG] Invalid JSON value for Type TiTableInfo because of tiflash_replica

### ISSUE THREAD

**Issue by marsishandsome** [pingcap/tispark#1172]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tispark_regression_test_daily/detail/tispark_regression_test_daily/129/pipeline

```
 com.pingcap.tikv.exception.TiClientInternalException: Invalid JSON value for Type TiTableInfo: {"id":95,"name":{"O":"v","L":"v"},"charset":"utf8mb4","collate":"utf8mb4_bin","cols":[{"id":1,"name":{"O":"qty","L":"qty"},"offset":0,"origin_default":null,"default":null,"default_bit":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"state":5,"comment":"","version":0},{"id":2,"name":{"O":"price","L":"price"},"offset":1,"origin_default":null,"default":null,"default_bit":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"state":5,"comment":"","version":0},{"id":3,"name":{"O":"value","L":"value"},"offset":2,"origin_default":null,"default":null,"default_bit":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":0,"Flag":0,"Flen":0,"Decimal":0,"Charset":"","Collate":"","Elems":null},"state":5,"comment":"","version":0}],"index_info":null,"fk_info":null,"state":5,"pk_is_handle":false,"comment":"","auto_inc_id":0,"max_col_id":3,"max_idx_id":0,"update_timestamp":412142855434534914,"ShardRowIDBits":0,"max_shard_row_id_bits":0,"pre_split_regions":0,"partition":null,"compression":"","view":{"view_algorithm":0,"view_definer":{"Username":"root","Hostname":"127.0.0.1","CurrentUser":false,"AuthUsername":"root","AuthHostname":"%"},"view_security":0,"view_select":"SELECT `qty`,`price`,`qty`*`price` AS `value` FROM `tispark_test`.`test_view`","view_checkoption":1,"view_cols":null},"Lock":null,"version":3,"tiflash_replica":null}

[2019-10-27T18:19:32.489Z]   at com.pingcap.tikv.catalog.CatalogTransaction.parseFromJson(CatalogTransaction.java:95)

[2019-10-27T18:19:32.489Z]   at com.pingcap.tikv.catalog.CatalogTransaction.getTables(CatalogTransaction.java:77)

[2019-10-27T18:19:32.489Z]   at com.pingcap.tikv.catalog.Catalog$CatalogCache.loadTables(Catalog.java:95)

[2019-10-27T18:19:32.489Z]   at com.pingcap.tikv.catalog.Catalog$CatalogCache.getTable(Catalog.java:85)

[2019-10-27T18:19:32.489Z]   at com.pingcap.tikv.catalog.Catalog.getTable(Catalog.java:178)

[2019-10-27T18:19:32.489Z]   at com.pingcap.tikv.catalog.Catalog.getTable(Catalog.java:171)

[2019-10-27T18:19:32.489Z]   at com.pingcap.tispark.TiBatchWrite.doWrite(TiBatchWrite.scala:128)

[2019-10-27T18:19:32.489Z]   at com.pingcap.tispark.TiBatchWrite.com$pingcap$tispark$TiBatchWrite$$write(TiBatchWrite.scala:91)

[2019-10-27T18:19:32.489Z]   at com.pingcap.tispark.TiBatchWrite$.writeToTiDB(TiBatchWrite.scala:55)

[2019-10-27T18:19:32.489Z]   at com.pingcap.tispark.TiDBWriter$.write(TiDBWriter.scala:20)
```

**Comment by zhexuany** [comment]
It is fixed, closing.
