### ISSUE TITLE
Spark 2.2 compatibility test

### ISSUE THREAD

**Issue by ilovesoup** [pingcap/tispark#13]
I've tried tpch1 already and it worked as it is.
Need a full test after regression app done.

**Comment by worldgreen** [comment]
@ilovesoup    did you meet a exception ? like this  
18/08/03 14:00:55 ERROR ApplicationMaster: User class threw exception: java.lang.NoSuchMethodError: scala.reflect.api.JavaUniverse.runtimeMirror(Ljava/lang/ClassLoader;)Lscala/reflect/api/JavaUniverse$JavaMirror;
java.lang.NoSuchMethodError: scala.reflect.api.JavaUniverse.runtimeMirror(Ljava/lang/ClassLoader;)Lscala/reflect/api/JavaUniverse$JavaMirror;
	at com.pingcap.tispark.TiUtils$.sessionInitialize(TiUtils.scala:222)
	at org.apache.spark.sql.TiContext.<init>(TiContext.scala:42)
	at com.qiyi.passport.didmapping.DidmappingScala$.main(DidmappingScala.scala:12)
	at com.qiyi.passport.didmapping.DidmappingScala.main(DidmappingScala.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:635)
18

**Comment by birdstorm** [comment]
Spark 2.2 will be skipped. We will jump to Spark 2.3.
