### ISSUE TITLE
Error in pushdown aggregates with double arithmetic operation

### ISSUE THREAD

**Issue by ilovesoup** [pingcap/tispark#132]
```spark.sql(
      """select
        |   sum(1 - l_discount) as sum_charge
        |from
        |   lineitem
      """.stripMargin).show
```
On TPCH Q1

```
Caused by: com.pingcap.tikv.exception.SelectException: unknown error Other(StringError("Can\'t eval_decimal from Datum"))
  at com.pingcap.tikv.region.RegionStoreClient.coprocessorHelper(RegionStoreClient.java:268)
  at com.pingcap.tikv.region.RegionStoreClient.coprocess(RegionStoreClient.java:188)
  at com.pingcap.tikv.operation.iterator.DAGIterator.process(DAGIterator.java:161)
  at com.pingcap.tikv.operation.iterator.DAGIterator.lambda$submitTasks$1(DAGIterator.java:59)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
```

**Comment by Novemser** [comment]
Should be fixed in https://github.com/pingcap/tikv-client-lib-java/pull/191

**Comment by Novemser** [comment]
Should be added in integration test.
