### ISSUE TITLE
[BUG] Regression Test Failed: NPE when decoding datetime,date,timestamp

### ISSUE THREAD

**Issue by marsishandsome** [pingcap/tispark#1412]
Regression Test Failed: NPE when decoding datetime,date,timestamp

tidb branch: master
tispark branch: master & release-2.1

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tispark_regression_test_daily/detail/tispark_regression_test_daily/381/pipeline/

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tispark_regression_test_daily/detail/tispark_regression_test_daily/374/pipeline/

```
[2020-04-22T19:20:38.016Z] - NPE when decoding datetime,date,timestamp *** FAILED ***
[2020-04-22T19:20:38.017Z]   java.sql.SQLException: Incorrect datetime value: '0000-00-00 00:00:00' for column 'tp_datetime' at row 1
[2020-04-22T19:20:38.017Z]   at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964)
[2020-04-22T19:20:38.017Z]   at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
[2020-04-22T19:20:38.017Z]   at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
[2020-04-22T19:20:38.017Z]   at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
[2020-04-22T19:20:38.017Z]   at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
[2020-04-22T19:20:38.017Z]   at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2483)
[2020-04-22T19:20:38.017Z]   at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2441)
[2020-04-22T19:20:38.017Z]   at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:845)
[2020-04-22T19:20:38.017Z]   at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:745)
[2020-04-22T19:20:38.017Z]   at org.apache.spark.sql.IssueTestSuite$$anonfun$15.apply$mcV$sp(IssueTestSuite.scala:358)
```

**Comment by birdstorm** [comment]
Closed by #1425
