### ISSUE TITLE
[BUG] Regression Test Fail: support desc table

### ISSUE THREAD

**Issue by marsishandsome** [pingcap/tispark#1430]
tikv=v3.0.12 tidb=v3.0.12 pd=v3.0.12 mode=full region=small tispark-branch=release-2.1

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tispark_regression_test_daily/detail/tispark_regression_test_daily/609/pipeline/

```
[2020-05-09T22:06:10.929Z] - support desc table *** FAILED ***

[2020-05-09T22:06:10.929Z]   org.apache.spark.sql.AnalysisException: Hive support is required to CREATE Hive TABLE (AS SELECT);;

[2020-05-09T22:06:10.929Z] 'CreateTable `t`, org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe, ErrorIfExists

[2020-05-09T22:06:10.929Z]   at org.apache.spark.sql.execution.datasources.HiveOnlyCheck$$anonfun$apply$12.apply(rules.scala:392)

[2020-05-09T22:06:10.929Z]   at org.apache.spark.sql.execution.datasources.HiveOnlyCheck$$anonfun$apply$12.apply(rules.scala:390)

[2020-05-09T22:06:10.929Z]   at org.apache.spark.sql.catalyst.trees.TreeNode.foreach(TreeNode.scala:117)

[2020-05-09T22:06:10.929Z]   at org.apache.spark.sql.execution.datasources.HiveOnlyCheck$.apply(rules.scala:390)

[2020-05-09T22:06:10.929Z]   at org.apache.spark.sql.execution.datasources.HiveOnlyCheck$.apply(rules.scala:388)

[2020-05-09T22:06:10.929Z]   at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$2.apply(CheckAnalysis.scala:396)

[2020-05-09T22:06:10.929Z]   at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$2.apply(CheckAnalysis.scala:396)

[2020-05-09T22:06:10.929Z]   at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)

[2020-05-09T22:06:10.929Z]   at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)

[2020-05-09T22:06:10.929Z]   at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$class.checkAnalysis(CheckAnalysis.scala:396)

[2020-05-09T22:06:10.929Z]   ...
```

**Comment by birdstorm** [comment]
Closed by #1417
