### ISSUE TITLE
[BUG] oom when selecting from a large table

### ISSUE THREAD

**Issue by marsishandsome** [pingcap/tispark#1518]
oom when selecting from a large table

```
WARN channel.AbstractChannelHandlerContext: An exception 'shade.io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 7633633559, max: 7635730432)' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
shade.io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 7633633559, max: 7635730432)
	at shade.io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:667)
	at shade.io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:622)
	at shade.io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:772)
	at shade.io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:748)
	at shade.io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:245)
	at shade.io.netty.buffer.PoolArena.allocate(PoolArena.java:227)
	at shade.io.netty.buffer.PoolArena.allocate(PoolArena.java:147)
	at shade.io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:342)
	at shade.io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
	at shade.io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
	at shade.io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:115)
	at shade.io.netty.handler.codec.ByteToMessageDecoder.expandCumulation(ByteToMessageDecoder.java:532)
	at shade.io.netty.handler.codec.ByteToMessageDecoder$1.cumulate(ByteToMessageDecoder.java:92)
	at shade.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:281)
	at shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at shade.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at shade.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1421)
	at shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at shade.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at shade.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at shade.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:697)
	at shade.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at shade.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at shade.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511)
	at shade.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at shade.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at shade.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by birdstorm** [comment]
Same as #1504

**Comment by birdstorm** [comment]
Closed by https://github.com/pingcap/tispark/pull/1562/commits/dae3ec663abcb8b77eff09a27683066c977a47ad
