### ISSUE TITLE
Error parsing orderBy expressions

### ISSUE THREAD

**Issue by Novemser** [pingcap/tispark#160]
SQLs like
```sql
select l_returnflag from lineitem order by (l_returnflag,l_linenumber) limit 2
```

will throw
```java
java.util.NoSuchElementException: None.get
  at scala.None$.get(Option.scala:347)
  at scala.None$.get(Option.scala:345)
  at org.apache.spark.sql.TiStrategy$$anonfun$addSortOrder$1.apply(TiStrategy.scala:179)
  at org.apache.spark.sql.TiStrategy$$anonfun$addSortOrder$1.apply(TiStrategy.scala:176)
  at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
  at org.apache.spark.sql.TiStrategy.addSortOrder(TiStrategy.scala:175)
  at org.apache.spark.sql.TiStrategy.pruneTopNFilterProject(TiStrategy.scala:195)
  at org.apache.spark.sql.TiStrategy.takeOrderedAndProject(TiStrategy.scala:224)
  at org.apache.spark.sql.TiStrategy.org$apache$spark$sql$TiStrategy$$doPlan(TiStrategy.scala:418)
  at org.apache.spark.sql.TiStrategy$$anonfun$apply$1.applyOrElse(TiStrategy.scala:86)
  at org.apache.spark.sql.TiStrategy$$anonfun$apply$1.applyOrElse(TiStrategy.scala:84)
...
```

but
```sql
select l_returnflag from lineitem order by l_returnflag,l_linenumber limit 2
```

won't.

Seems there's some issue in handling `CreateNamedStruct` type `SortOrder` expressions.

**Comment by zhexuany** [comment]
@Novemser this could be problem from `SparkSQL`. Have you tested in Spark yet?

**Comment by birdstorm** [comment]
@zhexuany yes it has been confirmed.
