### ISSUE TITLE
select count(something + constant) reveals NPE on master branch

### ISSUE THREAD

**Issue by birdstorm** [pingcap/tispark#162]
```
scala> spark.sql("select count(tp_int + 1) from full_data_type_table").show
java.lang.NullPointerException
  at com.pingcap.tikv.expression.TiColumnRef.getType(TiColumnRef.java:84)
  at com.pingcap.tikv.expression.scalar.TiScalarFunction.getArgType(TiScalarFunction.java:61)
  at com.pingcap.tikv.expression.scalar.TiScalarFunction.getArgTypeCode(TiScalarFunction.java:72)
  at com.pingcap.tikv.expression.scalar.TiScalarFunction.getSignature(TiScalarFunction.java:44)
  at com.pingcap.tikv.expression.scalar.TiScalarFunction.getName(TiScalarFunction.java:51)
  at com.pingcap.tikv.expression.TiFunctionExpression.toString(TiFunctionExpression.java:123)
  at com.google.guava4pingcap.base.Joiner.toString(Joiner.java:448)
  at com.google.guava4pingcap.base.Joiner$2.appendTo(Joiner.java:257)
  at com.google.guava4pingcap.base.Joiner.appendTo(Joiner.java:154)
  at com.google.guava4pingcap.base.Joiner.join(Joiner.java:197)
  at com.google.guava4pingcap.base.Joiner.join(Joiner.java:186)
  at com.pingcap.tikv.expression.TiFunctionExpression.toString(TiFunctionExpression.java:124)
  at com.google.guava4pingcap.base.Joiner.toString(Joiner.java:448)
  at com.google.guava4pingcap.base.Joiner$2.appendTo(Joiner.java:257)
  at com.google.guava4pingcap.base.Joiner.appendTo(Joiner.java:154)
  at com.google.guava4pingcap.base.Joiner.join(Joiner.java:197)
  at com.google.guava4pingcap.base.Joiner.join(Joiner.java:186)
  at com.pingcap.tikv.meta.TiDAGRequest.toString(TiDAGRequest.java:606)
  at org.apache.spark.sql.execution.CoprocessorRDD.verboseString(CoprocessorRDD.scala:50)
  at org.apache.spark.sql.catalyst.trees.TreeNode.generateTreeString(TreeNode.scala:562)
  at org.apache.spark.sql.execution.InputAdapter.generateTreeString(WholeStageCodegenExec.scala:258)
  at org.apache.spark.sql.catalyst.trees.TreeNode.generateTreeString(TreeNode.scala:575)
  at org.apache.spark.sql.execution.WholeStageCodegenExec.generateTreeString(WholeStageCodegenExec.scala:432)
  at org.apache.spark.sql.catalyst.trees.TreeNode.generateTreeString(TreeNode.scala:575)
  at org.apache.spark.sql.execution.InputAdapter.generateTreeString(WholeStageCodegenExec.scala:258)
  at org.apache.spark.sql.catalyst.trees.TreeNode.generateTreeString(TreeNode.scala:575)
  at org.apache.spark.sql.execution.WholeStageCodegenExec.generateTreeString(WholeStageCodegenExec.scala:432)
  at org.apache.spark.sql.catalyst.trees.TreeNode.generateTreeString(TreeNode.scala:575)
  at org.apache.spark.sql.catalyst.trees.TreeNode.treeString(TreeNode.scala:487)
  at org.apache.spark.sql.execution.QueryExecution$$anonfun$toString$3.apply(QueryExecution.scala:232)
  at org.apache.spark.sql.execution.QueryExecution$$anonfun$toString$3.apply(QueryExecution.scala:232)
  at org.apache.spark.sql.execution.QueryExecution.stringOrError(QueryExecution.scala:107)
  at org.apache.spark.sql.execution.QueryExecution.toString(QueryExecution.scala:232)
  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:54)
  at org.apache.spark.sql.Dataset.withNewExecutionId(Dataset.scala:2765)
  at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$execute$1(Dataset.scala:2370)
  at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$collect(Dataset.scala:2377)
  at org.apache.spark.sql.Dataset$$anonfun$head$1.apply(Dataset.scala:2113)
  at org.apache.spark.sql.Dataset$$anonfun$head$1.apply(Dataset.scala:2112)
  at org.apache.spark.sql.Dataset.withTypedCallback(Dataset.scala:2795)
  at org.apache.spark.sql.Dataset.head(Dataset.scala:2112)
  at org.apache.spark.sql.Dataset.take(Dataset.scala:2327)
  at org.apache.spark.sql.Dataset.showString(Dataset.scala:248)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:636)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:595)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:604)
  ... 48 elided
```

**Comment by Novemser** [comment]
Need to add integration test cases after fix.
