### ISSUE TITLE
[BUG] com.pingcap.tikv.codec.MyDecimal cannot be cast to java.math.BigDecimal

### ISSUE THREAD

**Issue by Dieken** [pingcap/tispark#1625]
**Describe the bug**

```
2020-09-20 21:44:57.068 WARN TaskSetManager: Lost task 5.0 in stage 18.0 (TID 1908, 172.18.5.47, executor 6): java.lang.ClassCastException: com.pingcap.tikv.codec.MyDecimal cannot be cast to java.math.BigDecimal
	at com.pingcap.tikv.codec.RowEncoderV2.encodeDecimal(RowEncoderV2.java:320)
	at com.pingcap.tikv.codec.RowEncoderV2.encodeValue(RowEncoderV2.java:221)
	at com.pingcap.tikv.codec.RowEncoderV2.encodeRowCols(RowEncoderV2.java:166)
	at com.pingcap.tikv.codec.RowEncoderV2.encode(RowEncoderV2.java:61)
	at com.pingcap.tikv.codec.TableCodecV2.encodeRow(TableCodecV2.java:49)
	at com.pingcap.tikv.codec.TableCodec.encodeRow(TableCodec.java:38)
	at com.pingcap.tispark.write.TiBatchWriteTable.encodeTiRow(TiBatchWriteTable.scala:593)
	at com.pingcap.tispark.write.TiBatchWriteTable.com$pingcap$tispark$write$TiBatchWriteTable$$generateRowKey(TiBatchWriteTable.scala:679)
	at com.pingcap.tispark.write.TiBatchWriteTable$$anonfun$generateRecordKV$1.apply(TiBatchWriteTable.scala:687)
	at com.pingcap.tispark.write.TiBatchWriteTable$$anonfun$generateRecordKV$1.apply(TiBatchWriteTable.scala:685)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:193)
	at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:62)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
	at org.apache.spark.scheduler.Task.run(Task.scala:123)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**What did you do**

The `df` contains some `decimal(22, 8)` columns.

```java
        Map<String, String> tidbOptions = new HashMap<>();
        tidbOptions.put("tidb.addr", config.getProperty("tidb.addr", "127.0.0.1").trim());
        tidbOptions.put("tidb.port", config.getProperty("tidb.port", "4000").trim());
        tidbOptions.put("tidb.user", config.getProperty("tidb.user", "root").trim());
        tidbOptions.put("tidb.password", config.getProperty("tidb.password", "").trim());
        tidbOptions.put("replace", "true");
        tidbOptions.put("useTableLock", "false");

             df.write()
                .format("tidb")
                .options(tidbOptions)
                .option("database", "test")
                .option("table", "t)
                .mode(SaveMode.Append)
                .save();
```

**What do you expect**

Successfully write to TiDB.

**What happens instead**

TiSpark throws exception.

**Spark and TiSpark version info**

* TiDB: 5.7.25-TiDB-v4.0.1
* TiSpark: 2.3.4
* Spark: 2.4.7
* JDK: 1.8

**Comment by Dieken** [comment]
seems same issue with https://github.com/pingcap/tispark/issues/1622.

**Comment by birdstorm** [comment]
Closing along with #1622
