### ISSUE TITLE
[BUG]  NoSuchMethodError Exception: Compatibility Issues with spark 2.4.5

### ISSUE THREAD

**Issue by dawnbreaks** [pingcap/tispark#1634]
**Describe the bug**

NoSuchMethodError Exception in spark 2.4.5, please refer to the following exception  stacktrace and the [spark source file](https://github.com/apache/spark/blob/v2.4.5/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/catalog/interface.scala#L228)
```
User class threw exception: java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.catalog.CatalogTable.<init>(Lorg/apache/spark/sql/catalyst/TableIdentifier;Lorg/apache/spark/sql/catalyst/catalog/CatalogTableType;Lorg/apache/spark/sql/catalyst/catalog/CatalogStorageFormat;Lorg/apache/spark/sql/types/StructType;Lscala/Option;Lscala/collection/Seq;Lscala/Option;Ljava/lang/String;JJLjava/lang/String;Lscala/collection/immutable/Map;Lscala/Option;Lscala/Option;Lscala/Option;Lscala/collection/Seq;ZZLscala/collection/immutable/Map;)V
at org.apache.spark.sql.execution.command.TiCreateTableLikeCommand.run(tables.scala:308)
at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:79)
at org.apache.spark.sql.Dataset$$anonfun$6.apply(Dataset.scala:196)
at org.apache.spark.sql.Dataset$$anonfun$6.apply(Dataset.scala:196)
at org.apache.spark.sql.Dataset$$anonfun$52$$anonfun$apply$21.apply(Dataset.scala:3447)
at org.apache.spark.sql.execution.SQLExecution$.withNewTransactionId(SQLExecution.scala:99)
at org.apache.spark.sql.Dataset$$anonfun$52.apply(Dataset.scala:3446)
at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:82)
at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:147)
at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:77)
at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3444)
at org.apache.spark.sql.Dataset.<init>(Dataset.scala:196)
at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:80)
at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:663)
```

**What did you do**
just run a create table like sql.

**What do you expect**
No exception

**What happens instead**
NoSuchMethodError 

**Spark and TiSpark version info**
spark 2.4.5
tispark 2.3.4

**Comment by marsishandsome** [comment]
@dawnbreaks would you please run the following code?
```
spark.sql("select ti_version()").show(false)
```

**Comment by windtalker** [comment]
@dawnbreaks what is your Java version?

**Comment by dawnbreaks** [comment]
java version
```
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
```
select ti_version()
```
Release Version: 2.3.4
Git Commit Hash: ef25a689cef1a9ce1d7ab6800e55bdc7fc174183
Git Branch: release-2.3
UTC Build Time: 2020-09-15 03:54:30
Supported Spark Version: 2.3 2.4
Current Spark Version: 2.4.5
Current Spark Major Version: 2.4
TimeZone: Asia/Shanghai
Time taken: 1.755 seconds, Fetched 1 row(s)
```

**Comment by dawnbreaks** [comment]
@windtalker  Obviously this is a bug，The number of parameters of the CatalogTable construction method is different from that of spark 2.3

**Comment by windtalker** [comment]
But according to the [spark source file](https://github.com/apache/spark/blob/v2.4.5/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/catalog/interface.scala#L228), looks like the missing method is exactly the same as show in the spark source code, could you please double check the spark jars you using?

**Comment by windtalker** [comment]
And I don't see any difference of CatalogTable construction method between [spark 2.4.5](https://github.com/apache/spark/blob/v2.4.5/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/catalog/interface.scala#L228) and [spark 2.3.4](https://github.com/apache/spark/blob/v2.3.4/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/catalog/interface.scala#L213)

**Comment by dawnbreaks** [comment]
@windtalker  Oh my gosh, We are using aliyun Cloud's EMR service, we decompiled the spark-catalyst_2.11-2.4.5.jar file，found that the CatalogTable class definition had been changed by aliyun EMR team.

**Comment by windtalker** [comment]
> @windtalker Oh my gosh, We are using aliyun Cloud's EMR service, we decompiled the spark-catalyst_2.11-2.4.5.jar file，found that the CatalogTable class definition had been changed by aliyun EMR team.

OK, so sounds not a TiSpark bug, maybe you can try with the official spark jars.
