### ISSUE TITLE
[BUG]I catch a Exception : java.lang.ClassCastException: com.pingcap.tikv.codec.MyDecimal cannot be cast to java.math.BigDecimal ,how can I solve it ?

### ISSUE THREAD

**Issue by RUIzg** [pingcap/tispark#1687]
I got it when I run TiDataSourceExampleWithExtensions file

java.lang.ClassCastException: com.pingcap.tikv.codec.MyDecimal cannot be cast to java.math.BigDecimal
at com.pingcap.tikv.codec.RowEncoderV2.encodeDecimal(RowEncoderV2.java:320)
at com.pingcap.tikv.codec.RowEncoderV2.encodeValue(RowEncoderV2.java:221)
at com.pingcap.tikv.codec.RowEncoderV2.encodeRowCols(RowEncoderV2.java:166)
at com.pingcap.tikv.codec.RowEncoderV2.encode(RowEncoderV2.java:61)
at com.pingcap.tikv.codec.TableCodecV2.encodeRow(TableCodecV2.java:49)
at com.pingcap.tikv.codec.TableCodec.encodeRow(TableCodec.java:38)
at com.pingcap.tispark.write.TiBatchWriteTable.encodeTiRow(TiBatchWriteTable.scala:593)
at com.pingcap.tispark.write.TiBatchWriteTable.com$pingcap$tispark$write$TiBatchWriteTable$$generateRowKey(TiBatchWriteTable.scala:679)
at com.pingcap.tispark.write.TiBatchWriteTable$$anonfun$generateRecordKV$1.apply(TiBatchWriteTable.scala:687)
at com.pingcap.tispark.write.TiBatchWriteTable$$anonfun$generateRecordKV$1.apply(TiBatchWriteTable.scala:685)
at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
at org.apache.spark.storage.memory.MemoryStore.putIterator(MemoryStore.scala:222)
at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:299)
at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1165)
at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1156)
at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:1091)
at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1156)
at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:882)
at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:357)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:308)
at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
at org.apache.spark.scheduler.Task.run(Task.scala:123)
at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
20/10/23 07:21:22 ERROR TaskSetManager: Task 0 in stage 4.0 failed 1 times; aborting job
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 4.0 failed 1 times, most recent failure: Lost task 0.0 in stage 4.0 (TID 4, localhost, executor driver): java.lang.ClassCastException: com.pingcap.tikv.codec.MyDecimal cannot be cast to java.math.BigDecimal
at com.pingcap.tikv.codec.RowEncoderV2.encodeDecimal(RowEncoderV2.java:320)
at com.pingcap.tikv.codec.RowEncoderV2.encodeValue(RowEncoderV2.java:221)
at com.pingcap.tikv.codec.RowEncoderV2.encodeRowCols(RowEncoderV2.java:166)
at com.pingcap.tikv.codec.RowEncoderV2.encode(RowEncoderV2.java:61)
at com.pingcap.tikv.codec.TableCodecV2.encodeRow(TableCodecV2.java:49)
at com.pingcap.tikv.codec.TableCodec.encodeRow(TableCodec.java:38)
at com.pingcap.tispark.write.TiBatchWriteTable.encodeTiRow(TiBatchWriteTable.scala:593)
at com.pingcap.tispark.write.TiBatchWriteTable.com$pingcap$tispark$write$TiBatchWriteTable$$generateRowKey(TiBatchWriteTable.scala:679)
at com.pingcap.tispark.write.TiBatchWriteTable$$anonfun$generateRecordKV$1.apply(TiBatchWriteTable.scala:687)
at com.pingcap.tispark.write.TiBatchWriteTable$$anonfun$generateRecordKV$1.apply(TiBatchWriteTable.scala:685)
at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
at org.apache.spark.storage.memory.MemoryStore.putIterator(MemoryStore.scala:222)
at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:299)
at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1165)
at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1156)
at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:1091)
at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1156)
at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:882)
at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:357)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:308)
at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
at org.apache.spark.scheduler.Task.run(Task.scala:123)
at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

**Comment by marsishandsome** [comment]
same as https://github.com/pingcap/tispark/issues/1625
fixed in https://github.com/pingcap/tispark/issues/1622
please try tispark-2.3.6
