### ISSUE TITLE
Error executing TPCH q1 in index scan mode

### ISSUE THREAD

**Issue by Novemser** [pingcap/tispark#169]
```scala
scala> q1.explain
com.pingcap.tikv.exception.CastingException: Cannot cast to Comparable for type: DateWrapper
  at com.pingcap.tikv.util.Comparables.wrap(Comparables.java:46)
  at com.pingcap.tikv.predicates.RangeBuilder.exprToRanges(RangeBuilder.java:124)
  at com.pingcap.tikv.predicates.RangeBuilder.exprsToIndexRanges(RangeBuilder.java:51)
  at com.pingcap.tikv.predicates.ScanBuilder.buildScan(ScanBuilder.java:116)
  at com.pingcap.tikv.predicates.ScanBuilder.buildScan(ScanBuilder.java:87)
  at org.apache.spark.sql.TiStrategy.filterToDAGRequest(TiStrategy.scala:187)
  at org.apache.spark.sql.TiStrategy.org$apache$spark$sql$TiStrategy$$doPlan(TiStrategy.scala:485)
```

Pushing down date constant type caused this issue.

**Comment by ilovesoup** [comment]
Please add test case to reproduce this first. Type system is under refactor now and we need to make sure this is captured later.

**Comment by ilovesoup** [comment]
@Novemser Please confirm in new master.

**Comment by ilovesoup** [comment]
Master has been tested against tpch.
