### ISSUE TITLE
[BUG] Insert value to column of json type raise a exception

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tispark#1702]
**Describe the bug**

Insert value to column of json type raise a exception
**What did you do**

1. execute in tidb
create table t1(jdoc json)
insert into t1 values('{"k1":"v1","k2":"v2"}')
2. execute in tispark
create table st using tidb options(table 't1')
insert into st select '{"k1":"v1","k2":"v2"}'

**What do you expect**

success
**What happens instead**

```
Caused by: com.pingcap.tikv.exception.ConvertNotSupportException: do not support converting from java.lang.String to  com.pingcap.tikv.types.JsonType
	at com.pingcap.tikv.types.JsonType.doConvertToTiDBType(JsonType.java:58)
	at com.pingcap.tikv.types.DataType.convertToTiDBType(DataType.java:395)
	at com.pingcap.tispark.write.TiBatchWriteTable$$anonfun$com$pingcap$tispark$write$TiBatchWriteTable$$sparkRow2TiKVRow$1.apply$mcVI$sp(TiBatchWriteTable.scala:560)
```

**Spark and TiSpark version info**

Git Commit Hash: 9687b70202584883fe5b88d39fb62d64867ebde2
Git Branch: release-2.3
UTC Build Time: 2020-10-16 02:40:15
Supported Spark Version: 2.3 2.4
Current Spark Version: 2.4.3
Current Spark Major Version: 2.4
TimeZone: Asia/Shanghai

TIDB: release-4.0

**Comment by marsishandsome** [comment]
currently tispark does not support writing to json type
