### ISSUE TITLE
[BUG] The select statement on enum type raise "index out of range" exception

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tispark#1740]
**Describe the bug**

The select statement on set type raise "index out of range" exception
**What did you do**

1. execute in tidb
```
set sql_mode='';
create table t(c enum("good","bad"));
insert into t values('');
insert into t values('hello');
insert into t values('bad');
insert into t values(null);
```
2. execute in tispark
```
select * from t1
```

**What do you expect**

'','','bad',null
**What happens instead**

```
com.pingcap.tikv.exception.TypeException: Index is out of range
	at com.pingcap.tikv.codec.Codec$EnumCodec.readEnumFromIndex(Codec.java:726)
	at com.pingcap.tikv.types.EnumType.decodeNotNull(EnumType.java:78)
	at com.pingcap.tikv.types.DataType.decode(DataType.java:323)
	at com.pingcap.tikv.row.DefaultRowReader.readRow(DefaultRowReader.java:43)
	at com.pingcap.tikv.operation.iterator.CoprocessorIterator$2.next(CoprocessorIterator.java:131)
	at com.pingcap.tikv.operation.iterator.CoprocessorIterator$2.next(CoprocessorIterator.java:122)
	at org.apache.spark.sql.tispark.TiRowRDD$$anon$1.next(TiRowRDD.scala:73)
	at org.apache.spark.sql.tispark.TiRowRDD$$anon$1.next(TiRowRDD.scala:50)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.coprocessorrdd_nextBatch_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:636)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:255)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:247)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:836)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:836)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
**Spark and TiSpark version info**

Git Commit Hash: 9687b70202584883fe5b88d39fb62d64867ebde2
Git Branch: release-2.3
UTC Build Time: 2020-10-16 02:40:15
Supported Spark Version: 2.3 2.4
Current Spark Version: 2.4.3
Current Spark Major Version: 2.4
TimeZone: Asia/Shanghai

TIDB: release-4.0

**Comment by birdstorm** [comment]
This is due to a bug in TiDB release-5.0. 

corresponding fix is https://github.com/pingcap/tidb/commit/be636811610b46b8650fd0fef4428169c1ac31ad
