### ISSUE TITLE
[BUG] when TiSpark write into TiDB table concurrently, it may throw `WriteConflict` error even no conflict will happen.

### ISSUE THREAD

**Issue by windtalker** [pingcap/tispark#1767]
**Describe the bug**

To reproduce, refer to TICASE-3433 in https://github.com/pingcap/automated-tests/pull/532
**What did you do**

**What do you expect**

**What happens instead**

**Spark and TiSpark version info**

**Comment by marsishandsome** [comment]
```
com.pingcap.tikv.exception.TiBatchWriteException: prewrite primary key error
        at com.pingcap.tikv.TwoPhaseCommitter.doPrewritePrimaryKeyWithRetry(TwoPhaseCommitter.java:167)
        at com.pingcap.tikv.TwoPhaseCommitter.prewritePrimaryKey(TwoPhaseCommitter.java:143)
        at com.pingcap.tikv.allocator.RowIDAllocator.set(RowIDAllocator.java:110)
        at com.pingcap.tikv.allocator.RowIDAllocator.updateHash(RowIDAllocator.java:173)
        at com.pingcap.tikv.allocator.RowIDAllocator.udpateAllocateId(RowIDAllocator.java:208)
        at com.pingcap.tikv.allocator.RowIDAllocator.initSigned(RowIDAllocator.java:251)
        at com.pingcap.tikv.allocator.RowIDAllocator.create(RowIDAllocator.java:87)
        at com.pingcap.tispark.write.TiBatchWriteTable.getRowIDAllocator(TiBatchWriteTable.scala:352)
        at com.pingcap.tispark.write.TiBatchWriteTable.preCalculate(TiBatchWriteTable.scala:225)
        at com.pingcap.tispark.write.TiBatchWrite$$anonfun$1.apply(TiBatchWrite.scala:193)
        at com.pingcap.tispark.write.TiBatchWrite$$anonfun$1.apply(TiBatchWrite.scala:193)
        at scala.collection.immutable.List.map(List.scala:284)
        at com.pingcap.tispark.write.TiBatchWrite.doWrite(TiBatchWrite.scala:193)
        at com.pingcap.tispark.write.TiBatchWrite.com$pingcap$tispark$write$TiBatchWrite$$write(TiBatchWrite.scala:87)
        at com.pingcap.tispark.write.TiBatchWrite$.write(TiBatchWrite.scala:45)
        at com.pingcap.tispark.write.TiDBWriter$.write(TiDBWriter.scala:40)
        at com.pingcap.tispark.TiDBRelation.insert(TiDBRelation.scala:143)
        at org.apache.spark.sql.execution.datasources.InsertIntoDataSourceCommand.run(InsertIntoDataSourceCommand.scala:42)
```

**Comment by marsishandsome** [comment]
```
com.pingcap.tikv.exception.TiBatchWriteException: prewrite primary key error
        at com.pingcap.tikv.TwoPhaseCommitter.doPrewritePrimaryKeyWithRetry(TwoPhaseCommitter.java:167)
        at com.pingcap.tikv.TwoPhaseCommitter.doPrewritePrimaryKeyWithRetry(TwoPhaseCommitter.java:177)
        at com.pingcap.tikv.TwoPhaseCommitter.prewritePrimaryKey(TwoPhaseCommitter.java:143)
        at com.pingcap.tispark.write.TiBatchWrite.doWrite(TiBatchWrite.scala:261)
        at com.pingcap.tispark.write.TiBatchWrite.com$pingcap$tispark$write$TiBatchWrite$$write(TiBatchWrite.scala:87)
        at com.pingcap.tispark.write.TiBatchWrite$.write(TiBatchWrite.scala:45)
        at com.pingcap.tispark.write.TiDBWriter$.write(TiDBWriter.scala:40)
        at com.pingcap.tispark.TiDBRelation.insert(TiDBRelation.scala:143)
        at org.apache.spark.sql.execution.datasources.InsertIntoDataSourceCommand.run(InsertIntoDataSourceCommand.scala:42)
```

**Comment by marsishandsome** [comment]
```
20/12/04 15:44:10 WARN TaskSetManager: Lost task 0.0 in stage 278.0 (TID 868, 127.0.0.1, executor 0): com.pingcap.tikv.exception.TiBatchWriteException: Execution exception met.
        at com.pingcap.tikv.TwoPhaseCommitter.doPrewriteSecondaryKeys(TwoPhaseCommitter.java:305)
        at com.pingcap.tikv.TwoPhaseCommitter.prewriteSecondaryKeys(TwoPhaseCommitter.java:258)
        at com.pingcap.tispark.write.TiBatchWrite$$anonfun$doWrite$7.apply(TiBatchWrite.scala:295)
        at com.pingcap.tispark.write.TiBatchWrite$$anonfun$doWrite$7.apply(TiBatchWrite.scala:278)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$28.apply(RDD.scala:935)
        at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$28.apply(RDD.scala:935)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2101)
        at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2101)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:121)
        at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: com.pingcap.tikv.exception.TiBatchWriteException: prewrite secondary key error
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.pingcap.tikv.TwoPhaseCommitter.doPrewriteSecondaryKeys(TwoPhaseCommitter.java:298)
        ... 15 more
Caused by: com.pingcap.tikv.exception.TiBatchWriteException: prewrite secondary key error
        at com.pingcap.tikv.TwoPhaseCommitter.doPrewriteSecondaryKeySingleBatchWithRetry(TwoPhaseCommitter.java:424)
        at com.pingcap.tikv.TwoPhaseCommitter.doPrewriteSecondaryKeysInBatchesWithRetry(TwoPhaseCommitter.java:355)
        at com.pingcap.tikv.TwoPhaseCommitter.lambda$doPrewriteSecondaryKeys$0(TwoPhaseCommitter.java:289)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        ... 3 more
Caused by: com.pingcap.tikv.exception.KeyException: retryable: "Txn(Mvcc(WriteConflict { start_ts: TimeStamp(421283192972509189), conflict_start_ts: TimeStamp(421283192972509188), conflict_commit_ts: TimeStamp(421283194388348929), key: [116, 128, 0, 0, 0, 0, 0, 8, 87, 95, 105, 128, 0, 0, 0, 0, 0, 0, 1, 3, 128, 0, 0, 0, 0, 0, 1, 49], primary: [116, 128, 0, 0, 0, 0, 0, 8, 87, 95, 114, 128, 0, 0, 0, 0, 30, 132, 144] }))"
conflict {
  start_ts: 421283192972509189
  conflict_ts: 421283192972509188
  key: "t\200\000\000\000\000\000\bW_i\200\000\000\000\000\000\000\001\003\200\000\000\000\000\000\0011"
  primary: "t\200\000\000\000\000\000\bW_r\200\000\000\000\000\036\204\220"
  conflict_commit_ts: 421283194388348929
}

        at com.pingcap.tikv.region.RegionStoreClient.isPrewriteSuccess(RegionStoreClient.java:483)
        at com.pingcap.tikv.region.RegionStoreClient.prewrite(RegionStoreClient.java:448)
        at com.pingcap.tikv.region.RegionStoreClient.prewrite(RegionStoreClient.java:395)
        at com.pingcap.tikv.txn.TxnKVClient.prewrite(TxnKVClient.java:102)
        at com.pingcap.tikv.TwoPhaseCommitter.doPrewriteSecondaryKeySingleBatchWithRetry(TwoPhaseCommitter.java:414)
        ... 8 more

```

**Comment by marsishandsome** [comment]
```
Caused by: com.pingcap.tikv.exception.WriteConflictException: callerStartTS=421283198477795329 txnID=421283198477795330 commitTS=0 key=*
        at com.pingcap.tikv.txn.LockResolverClientV4.resolveLocks(LockResolverClientV4.java:139)
        at com.pingcap.tikv.region.RegionStoreClient.isPrewriteSuccess(RegionStoreClient.java:491)
        at com.pingcap.tikv.region.RegionStoreClient.prewrite(RegionStoreClient.java:448)
        at com.pingcap.tikv.region.RegionStoreClient.prewrite(RegionStoreClient.java:395)
        at com.pingcap.tikv.txn.TxnKVClient.prewrite(TxnKVClient.java:102)
        at com.pingcap.tikv.TwoPhaseCommitter.doPrewritePrimaryKeyWithRetry(TwoPhaseCommitter.java:164)
        ... 49 more
```

**Comment by marsishandsome** [comment]
closed by https://github.com/pingcap/tispark/pull/1856
