### ISSUE TITLE
[BUG] TiDAGRequest does not support concurrent visit

### ISSUE THREAD

**Issue by marsishandsome** [pingcap/tispark#1894]
tispark throws the following exception
```
Caused by: java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
        at java.util.ArrayList$Itr.next(ArrayList.java:851)
        at com.pingcap.com.google.common.base.Joiner$2.appendTo(Joiner.java:260)
        at com.pingcap.com.google.common.base.Joiner.appendTo(Joiner.java:152)
        at com.pingcap.com.google.common.base.Joiner.appendTo(Joiner.java:139)
        at com.pingcap.tikv.meta.TiDAGRequest.toString(TiDAGRequest.java:964)
        at java.lang.String.valueOf(String.java:2994)
        at java.lang.StringBuilder.append(StringBuilder.java:131)
        at scala.StringContext.standardInterpolator(StringContext.scala:125)
        at scala.StringContext.s(StringContext.scala:95)
        at org.apache.spark.sql.execution.LeafColumnarExecRDD$class.verboseString(CoprocessorRDD.scala:63)                                                               
        at org.apache.spark.sql.execution.ColumnarCoprocessorRDD.verboseString(CoprocessorRDD.scala:70)                                                                  
        at org.apache.spark.sql.catalyst.trees.TreeNode.generateTreeString(TreeNode.scala:556)                                                                           
        at org.apache.spark.sql.catalyst.trees.TreeNode.generateTreeString(TreeNode.scala:576)                                                                           
        at org.apache.spark.sql.catalyst.trees.TreeNode.generateTreeString(TreeNode.scala:576)                                                                           
        at org.apache.spark.sql.execution.WholeStageCodegenExec.generateTreeString(WholeStageCodegenExec.scala:670)                                                      
        at org.apache.spark.sql.catalyst.trees.TreeNode.generateTreeString(TreeNode.scala:576)                                                                           
        at org.apache.spark.sql.execution.adaptive.QueryStage.generateTreeString(QueryStage.scala:203)                                                                   
        at org.apache.spark.sql.execution.adaptive.QueryStageInput.generateTreeString(QueryStageInput.scala:72)                                                          
        at org.apache.spark.sql.catalyst.trees.TreeNode.generateTreeString(TreeNode.scala:576)                                                                           
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$generateTreeString$3.apply(TreeNode.scala:574)                                                          
        at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$generateTreeString$3.apply(TreeNode.scala:574)                                                          
        at scala.collection.immutable.List.foreach(List.scala:381)
        at org.apache.spark.sql.catalyst.trees.TreeNode.generateTreeString(TreeNode.scala:574)                                                                           
        at org.apache.spark.sql.catalyst.trees.TreeNode.generateTreeString(TreeNode.scala:576)                                                                           
        at org.apache.spark.sql.catalyst.trees.TreeNode.generateTreeString(TreeNode.scala:576)                                                                           
        at org.apache.spark.sql.execution.adaptive.QueryStage.generateTreeString(QueryStage.scala:203)                                                                   
        at org.apache.spark.sql.execution.adaptive.QueryStageInput.generateTreeString(QueryStageInput.scala:72)                                                          
        at org.apache.spark.sql.catalyst.trees.TreeNode.generateTreeString(TreeNode.scala:576)                                                                           
        at org.apache.spark.sql.execution.adaptive.QueryStage.generateTreeString(QueryStage.scala:203)                                                                   
        at org.apache.spark.sql.catalyst.trees.TreeNode.treeString(TreeNode.scala:480)                                                                                   
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$toString$3.apply(QueryExecution.scala:223)                                                             
        at org.apache.spark.sql.execution.QueryExecution$$anonfun$toString$3.apply(QueryExecution.scala:223)                                                             
        at org.apache.spark.sql.execution.QueryExecution.stringOrError(QueryExecution.scala:115)                                                                         
        at org.apache.spark.sql.execution.QueryExecution.toString(QueryExecution.scala:223)                                                                              
        at org.apache.spark.sql.execution.adaptive.QueryStage.prepareExecuteStage(QueryStage.scala:158) 
```

**Comment by birdstorm** [comment]
closed by #1893
