### ISSUE TITLE
Using Max Func In A Column Which Is Datetime Type

### ISSUE THREAD

**Issue by wsabc01** [pingcap/tispark#219]
In tispark , it can not using max/min func in a column which is datetime type,My schema  information and error is below. Now , I use "cast(a as String)" as replace ，this error seems it translate to a wrong data structures.  
schema in tidb:
````
create table jiuan ( a datetime)
````
error:
````
scala> spark.sql("select max(a) ,min(a) from jiuan").show()
18/01/19 11:45:59 ERROR Executor: Exception in task 0.0 in stage 8.0 (TID 7)
java.lang.UnsupportedOperationException: only support cast to Long, Double and String
	at com.pingcap.tikv.operation.transformer.Cast.set(Cast.java:45)
	at com.pingcap.tikv.operation.transformer.RowTransformer.transform(RowTransformer.java:106)
	at org.apache.spark.sql.tispark.TiRDD$$anon$2.toSparkRow(TiRDD.scala:68)
	at org.apache.spark.sql.tispark.TiRDD$$anon$2.next(TiRDD.scala:88)
	at org.apache.spark.sql.tispark.TiRDD$$anon$2.next(TiRDD.scala:55)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.agg_doAggregateWithoutKey$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:377)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:126)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
````
replace:
````
scala> spark.sql("select max(cast(a as String)) ,min(cast(a as String)) from jiuan").show()
+----------------------+----------------------+
|max(CAST(a AS STRING))|min(CAST(a AS STRING))|
+----------------------+----------------------+
|   2018-01-19 11:09:33|   2018-01-19 11:09:09|
+----------------------+----------------------+
````

**Comment by Novemser** [comment]
This has been fix in PR https://github.com/pingcap/tispark/pull/202 just a few days before, please fetch the latest `master` branch code and have a try, thanks. : ) @wsabc01
