### ISSUE TITLE
[BUG] TiExpressionException: Cannot encode row key with non-long type

### ISSUE THREAD

**Issue by zzzzming95** [pingcap/tispark#2290]
**Describe the bug**

create table with `BITINT UNSIGNED` primary key, when run sample SQL with range predicate, i will meet `TiExpressionException: Cannot encode row key with non-long type`. 

**What did you do**

first , create sample table in mysql client.
```
CREATE TABLE `test` (
  `id` BIGINT(20) UNSIGNED  NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `age` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
```

than , run sample sql with range predicate, than will meet the exception. like 

> ./bin/spark-sql --jars ~/tispark-assembly-2.4.3-scala_2.11.jar

> SELECT * FROM test.test WHERE id >= 0 LIMIT 10;

**What happens instead**

full stack:
```
com.pingcap.tikv.exception.TiExpressionException: Cannot encode row key with non-long type
    at com.pingcap.tikv.key.RowKey.toRowKey(RowKey.java:64)
    at com.pingcap.tikv.predicates.TiKVScanAnalyzer.buildTableScanKeyRangePerId(TiKVScanAnalyzer.java:321)
    at com.pingcap.tikv.predicates.TiKVScanAnalyzer.lambda$buildTableScanKeyRangeWithIds$0(TiKVScanAnalyzer.java:349)
    at java.lang.Iterable.forEach(Iterable.java:75)
    at com.pingcap.tikv.predicates.TiKVScanAnalyzer.buildTableScanKeyRangeWithIds(TiKVScanAnalyzer.java:347)
    at com.pingcap.tikv.predicates.TiKVScanAnalyzer.buildTableScanKeyRange(TiKVScanAnalyzer.java:376)
    at com.pingcap.tikv.predicates.TiKVScanAnalyzer.buildIndexScan(TiKVScanAnalyzer.java:273)
    at com.pingcap.tikv.predicates.TiKVScanAnalyzer.buildTableScan(TiKVScanAnalyzer.java:228)
    at com.pingcap.tikv.predicates.TiKVScanAnalyzer.buildTiDAGReq(TiKVScanAnalyzer.java:162)
    at org.apache.spark.sql.TiStrategy.filterToDAGRequest(TiStrategy.scala:295)
    at org.apache.spark.sql.TiStrategy.pruneFilterProject(TiStrategy.scala:417)
    at org.apache.spark.sql.TiStrategy.pruneTopNFilterProject(TiStrategy.scala:320)
    at org.apache.spark.sql.TiStrategy.collectLimit(TiStrategy.scala:327)
    at org.apache.spark.sql.TiStrategy.org$apache$spark$sql$TiStrategy$$doPlan(TiStrategy.scala:573)
    at org.apache.spark.sql.TiStrategy$$anonfun$apply$1.applyOrElse(TiStrategy.scala:119)
    at org.apache.spark.sql.TiStrategy$$anonfun$apply$1.applyOrElse(TiStrategy.scala:117)
    at scala.PartialFunction$Lifted.apply(PartialFunction.scala:223)
    at scala.PartialFunction$Lifted.apply(PartialFunction.scala:219)
    at org.apache.spark.sql.catalyst.trees.TreeNode.collectFirst(TreeNode.scala:175)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3$$anonfun$apply$4.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3$$anonfun$apply$4.apply(TreeNode.scala:176)
    at scala.Option.orElse(Option.scala:289)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3.apply(TreeNode.scala:176)
    at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
    at scala.collection.immutable.List.foldLeft(List.scala:84)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1.apply(TreeNode.scala:176)
    at scala.Option.orElse(Option.scala:289)
    at org.apache.spark.sql.catalyst.trees.TreeNode.collectFirst(TreeNode.scala:175)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3$$anonfun$apply$4.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3$$anonfun$apply$4.apply(TreeNode.scala:176)
    at scala.Option.orElse(Option.scala:289)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3.apply(TreeNode.scala:176)
    at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
    at scala.collection.immutable.List.foldLeft(List.scala:84)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1.apply(TreeNode.scala:176)
    at scala.Option.orElse(Option.scala:289)
    at org.apache.spark.sql.catalyst.trees.TreeNode.collectFirst(TreeNode.scala:175)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3$$anonfun$apply$4.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3$$anonfun$apply$4.apply(TreeNode.scala:176)
    at scala.Option.orElse(Option.scala:289)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3.apply(TreeNode.scala:176)
    at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
    at scala.collection.immutable.List.foldLeft(List.scala:84)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1.apply(TreeNode.scala:176)
    at scala.Option.orElse(Option.scala:289)
    at org.apache.spark.sql.catalyst.trees.TreeNode.collectFirst(TreeNode.scala:175)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3$$anonfun$apply$4.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3$$anonfun$apply$4.apply(TreeNode.scala:176)
    at scala.Option.orElse(Option.scala:289)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3.apply(TreeNode.scala:176)
    at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
    at scala.collection.immutable.List.foldLeft(List.scala:84)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1.apply(TreeNode.scala:176)
    at scala.Option.orElse(Option.scala:289)
    at org.apache.spark.sql.catalyst.trees.TreeNode.collectFirst(TreeNode.scala:175)
    at org.apache.spark.sql.TiStrategy.apply(TiStrategy.scala:117)
    at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:63)
    at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:63)
    at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
    at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
    at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
    at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
    at org.apache.spark.sql.execution.QueryExecution.sparkPlan$lzycompute(QueryExecution.scala:73)
    at org.apache.spark.sql.execution.QueryExecution.sparkPlan(QueryExecution.scala:69)
    at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:78)
    at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:78)
    at org.apache.spark.sql.execution.QueryExecution$$anonfun$toString$3.apply(QueryExecution.scala:209)
    at org.apache.spark.sql.execution.QueryExecution$$anonfun$toString$3.apply(QueryExecution.scala:209)
    at org.apache.spark.sql.execution.QueryExecution.stringOrError(QueryExecution.scala:101)
    at org.apache.spark.sql.execution.QueryExecution.toString(QueryExecution.scala:209)
    at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:77)
    at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:145)
    at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:75)
    at org.apache.spark.sql.hive.thriftserver.SparkSQLDriver.run(SparkSQLDriver.scala:71)
    at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.processCmd(SparkSQLCLIDriver.scala:393)
    at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:376)
    at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver$.main(SparkSQLCLIDriver.scala:278)
    at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.main(SparkSQLCLIDriver.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
    at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:866)
    at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:184)
    at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:212)
    at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
    at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:941)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:950)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
com.pingcap.tikv.exception.TiExpressionException: Cannot encode row key with non-long type
    at com.pingcap.tikv.key.RowKey.toRowKey(RowKey.java:64)
    at com.pingcap.tikv.predicates.TiKVScanAnalyzer.buildTableScanKeyRangePerId(TiKVScanAnalyzer.java:321)
    at com.pingcap.tikv.predicates.TiKVScanAnalyzer.lambda$buildTableScanKeyRangeWithIds$0(TiKVScanAnalyzer.java:349)
    at java.lang.Iterable.forEach(Iterable.java:75)
    at com.pingcap.tikv.predicates.TiKVScanAnalyzer.buildTableScanKeyRangeWithIds(TiKVScanAnalyzer.java:347)
    at com.pingcap.tikv.predicates.TiKVScanAnalyzer.buildTableScanKeyRange(TiKVScanAnalyzer.java:376)
    at com.pingcap.tikv.predicates.TiKVScanAnalyzer.buildIndexScan(TiKVScanAnalyzer.java:273)
    at com.pingcap.tikv.predicates.TiKVScanAnalyzer.buildTableScan(TiKVScanAnalyzer.java:228)
    at com.pingcap.tikv.predicates.TiKVScanAnalyzer.buildTiDAGReq(TiKVScanAnalyzer.java:162)
    at org.apache.spark.sql.TiStrategy.filterToDAGRequest(TiStrategy.scala:295)
    at org.apache.spark.sql.TiStrategy.pruneFilterProject(TiStrategy.scala:417)
    at org.apache.spark.sql.TiStrategy.pruneTopNFilterProject(TiStrategy.scala:320)
    at org.apache.spark.sql.TiStrategy.collectLimit(TiStrategy.scala:327)
    at org.apache.spark.sql.TiStrategy.org$apache$spark$sql$TiStrategy$$doPlan(TiStrategy.scala:573)
    at org.apache.spark.sql.TiStrategy$$anonfun$apply$1.applyOrElse(TiStrategy.scala:119)
    at org.apache.spark.sql.TiStrategy$$anonfun$apply$1.applyOrElse(TiStrategy.scala:117)
    at scala.PartialFunction$Lifted.apply(PartialFunction.scala:223)
    at scala.PartialFunction$Lifted.apply(PartialFunction.scala:219)
    at org.apache.spark.sql.catalyst.trees.TreeNode.collectFirst(TreeNode.scala:175)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3$$anonfun$apply$4.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3$$anonfun$apply$4.apply(TreeNode.scala:176)
    at scala.Option.orElse(Option.scala:289)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3.apply(TreeNode.scala:176)
    at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
    at scala.collection.immutable.List.foldLeft(List.scala:84)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1.apply(TreeNode.scala:176)
    at scala.Option.orElse(Option.scala:289)
    at org.apache.spark.sql.catalyst.trees.TreeNode.collectFirst(TreeNode.scala:175)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3$$anonfun$apply$4.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3$$anonfun$apply$4.apply(TreeNode.scala:176)
    at scala.Option.orElse(Option.scala:289)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3.apply(TreeNode.scala:176)
    at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
    at scala.collection.immutable.List.foldLeft(List.scala:84)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1.apply(TreeNode.scala:176)
    at scala.Option.orElse(Option.scala:289)
    at org.apache.spark.sql.catalyst.trees.TreeNode.collectFirst(TreeNode.scala:175)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3$$anonfun$apply$4.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3$$anonfun$apply$4.apply(TreeNode.scala:176)
    at scala.Option.orElse(Option.scala:289)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3.apply(TreeNode.scala:176)
    at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
    at scala.collection.immutable.List.foldLeft(List.scala:84)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1.apply(TreeNode.scala:176)
    at scala.Option.orElse(Option.scala:289)
    at org.apache.spark.sql.catalyst.trees.TreeNode.collectFirst(TreeNode.scala:175)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3$$anonfun$apply$4.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3$$anonfun$apply$4.apply(TreeNode.scala:176)
    at scala.Option.orElse(Option.scala:289)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1$$anonfun$apply$3.apply(TreeNode.scala:176)
    at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
    at scala.collection.immutable.List.foldLeft(List.scala:84)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1.apply(TreeNode.scala:176)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$collectFirst$1.apply(TreeNode.scala:176)
    at scala.Option.orElse(Option.scala:289)
    at org.apache.spark.sql.catalyst.trees.TreeNode.collectFirst(TreeNode.scala:175)
    at org.apache.spark.sql.TiStrategy.apply(TiStrategy.scala:117)
    at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:63)
    at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:63)
    at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
    at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
    at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
    at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
    at org.apache.spark.sql.execution.QueryExecution.sparkPlan$lzycompute(QueryExecution.scala:73)
    at org.apache.spark.sql.execution.QueryExecution.sparkPlan(QueryExecution.scala:69)
    at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:78)
    at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:78)
    at org.apache.spark.sql.execution.QueryExecution$$anonfun$toString$3.apply(QueryExecution.scala:209)
    at org.apache.spark.sql.execution.QueryExecution$$anonfun$toString$3.apply(QueryExecution.scala:209)
    at org.apache.spark.sql.execution.QueryExecution.stringOrError(QueryExecution.scala:101)
    at org.apache.spark.sql.execution.QueryExecution.toString(QueryExecution.scala:209)
    at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:77)
    at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:145)
    at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:75)
    at org.apache.spark.sql.hive.thriftserver.SparkSQLDriver.run(SparkSQLDriver.scala:71)
    at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.processCmd(SparkSQLCLIDriver.scala:393)
    at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:376)
    at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver$.main(SparkSQLCLIDriver.scala:278)
    at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.main(SparkSQLCLIDriver.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
    at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:866)
    at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:184)
    at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:212)
    at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
    at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:941)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:950)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Spark and TiSpark version info**

spark version : spark2.4.0
tispark : 2.4.3-scala_2.11

**Comment by xuanyu66** [comment]
It's a bug caused by using `unsigned long` as the primary key. 
Due to historical reasons,  `unsigned long` must be split into two range requests. One is [0, MaxInt64], and another is [MaxInt64+1, MaxUint64]. 
https://github.com/pingcap/tidb/blob/master/distsql/request_builder.go#L445-L508
