### ISSUE TITLE
Client OOM on large data set

### ISSUE THREAD

**Issue by ilovesoup** [pingcap/tispark#23]
spark.sql(
     |       """select
     |         |    o_orderpriority,
     |         |    count(*) as order_count
     |         |from
     |         |    orders
     |         |where
     |         |    o_orderdate >= date '1993-07-01'
     |         |    and o_orderdate < date '1993-07-01' + interval '3' month
     |         |    and exists (
     |         |        select
     |         |            *
     |         |        from
     |         |            lineitem
     |         |        where
     |         |            l_orderkey = o_orderkey
     |         |            and l_commitdate < l_receiptdate
     |         |    )
     |         |group by
     |         |    o_orderpriority
     |         |order by
     |         |    o_orderpriority
     |       """.stripMargin).show
This is on scale factor 200.
com.pingcap.tikv.exception.TiClientInternalException: Error Closing Store client.
	at com.pingcap.tikv.operation.SelectIterator.lambda$new$1(SelectIterator.java:102)
	at com.pingcap.tikv.operation.SelectIterator.readNextRegion(SelectIterator.java:120)
	at com.pingcap.tikv.operation.SelectIterator.hasNext(SelectIterator.java:128)
	at com.pingcap.tispark.TiRDD$$anon$1.hasNext(TiRDD.scala:67)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:377)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:126)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.pingcap.tikv.exception.GrpcException: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: io.grpc.netty.NettyClientTransport$3: Frame size 81522888 exceeds maximum: 67108864.
	at com.pingcap.tikv.policy.RetryPolicy.callWithRetry(RetryPolicy.java:73)
	at com.pingcap.tikv.AbstractGrpcClient.callWithRetry(AbstractGrpcClient.java:54)
	at com.pingcap.tikv.region.RegionStoreClient.coprocess(RegionStoreClient.java:244)
	at com.pingcap.tikv.operation.SelectIterator.lambda$new$1(SelectIterator.java:94)
	... 17 more
Caused by: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: io.grpc.netty.NettyClientTransport$3: Frame size 81522888 exceeds maximum: 67108864.
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
	at com.pingcap.tikv.AbstractGrpcClient.lambda$callWithRetry$0(AbstractGrpcClient.java:56)
	at com.pingcap.tikv.policy.RetryPolicy.callWithRetry(RetryPolicy.java:58)
	... 20 more

**Comment by ilovesoup** [comment]
It seems not OOM but frame size exceeded. Need to make it configurable for large region size.

**Comment by zhexuany** [comment]
It is problem from TiKV side.
