### ISSUE TITLE
[BUG] When run JDBC TLS test, it reports a warn "closing inbound before receiving peer's close_notify"

### ISSUE THREAD

**Issue by Daemonxiao** [pingcap/tispark#2361]
**Describe the bug**

A Warn is reported when I run `com.pingcap.tispark.tls.JDBCTLSSuite.scala` test.

**What did you do**
When I used Corretto-1.8.0_332 JDK to run JDBC TLS test, I received some Warn.

1. set up environment
```
$ echo -e "127.0.0.1   pd \n127.0.0.1   tikv" | sudo tee -a /etc/hosts
$ sudo cp -r config /config
$ cp core/src/test/resources/tidb_config.properties.TLS.template core/src/test/resources/tidb_config.properties
$ docker-compose -f docker-compose-TiDB-TLS.yaml up
```
2. run test
```
$ mvn test -am -pl core -Dtest=moo -DwildcardSuites=com.pingcap.tispark.tls.JDBCTLSSuite -DfailIfNoTests=false
```

Then run 

**What do you expect**

```
Wed May 25 23:08:06 GMT-07:00 2022 WARN: Caught while disconnecting...

EXCEPTION STACK TRACE:



** BEGIN NESTED EXCEPTION ** 

javax.net.ssl.SSLException
MESSAGE: closing inbound before receiving peer's close_notify

STACKTRACE:

javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify
	at sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:740)
	at sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:719)
	at com.mysql.jdbc.MysqlIO.quit(MysqlIO.java:2246)
	at com.mysql.jdbc.ConnectionImpl.realClose(ConnectionImpl.java:4237)
	at com.mysql.jdbc.ConnectionImpl.close(ConnectionImpl.java:1465)
	at org.apache.spark.sql.test.SharedSQLContext.stop(SharedSQLContext.scala:307)
	at org.apache.spark.sql.test.SharedSQLContext.stop$(SharedSQLContext.scala:280)
	at com.pingcap.tispark.tls.JDBCTLSSuite.stop(JDBCTLSSuite.scala:22)
	at org.apache.spark.sql.test.SharedSQLContext.afterAll(SharedSQLContext.scala:271)
	at org.apache.spark.sql.test.SharedSQLContext.afterAll$(SharedSQLContext.scala:269)
	at com.pingcap.tispark.tls.JDBCTLSSuite.afterAll(JDBCTLSSuite.scala:39)
	at org.scalatest.BeforeAndAfterAll.$anonfun$run$1(BeforeAndAfterAll.scala:225)
	at org.scalatest.Status.$anonfun$withAfterEffect$1(Status.scala:379)
	at org.scalatest.Status.$anonfun$withAfterEffect$1$adapted(Status.scala:375)
	at org.scalatest.CompositeStatus.whenCompleted(Status.scala:886)
	at org.scalatest.Status.withAfterEffect(Status.scala:375)
	at org.scalatest.Status.withAfterEffect$(Status.scala:373)
	at org.scalatest.CompositeStatus.withAfterEffect(Status.scala:782)
	at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:224)
	at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
	at com.pingcap.tispark.tls.JDBCTLSSuite.run(JDBCTLSSuite.scala:22)
	at org.scalatest.Suite.callExecuteOnSuite$1(Suite.scala:1187)
	at org.scalatest.Suite.$anonfun$runNestedSuites$1(Suite.scala:1234)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at org.scalatest.Suite.runNestedSuites(Suite.scala:1232)
	at org.scalatest.Suite.runNestedSuites$(Suite.scala:1166)
	at org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:30)
	at org.scalatest.Suite.run(Suite.scala:1121)
	at org.scalatest.Suite.run$(Suite.scala:1106)
	at org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:30)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1349)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1343)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1343)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:1033)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:1011)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1509)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1011)
	at org.scalatest.tools.Runner$.main(Runner.scala:827)
	at org.scalatest.tools.Runner.main(Runner.scala)


** END NESTED EXCEPTION **


22/05/26 14:08:06 WARN TiSession: this TiSession is already closed!
22/05/26 14:08:06 INFO AbstractConnector: Stopped Spark@1136b469{HTTP/1.1, (http/1.1)}{0.0.0.0:4040}
22/05/26 14:08:06 INFO SparkUI: Stopped Spark web UI at http://192.168.1.12:4040
22/05/26 14:08:06 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
22/05/26 14:08:06 INFO MemoryStore: MemoryStore cleared
22/05/26 14:08:06 INFO BlockManager: BlockManager stopped
22/05/26 14:08:06 INFO BlockManagerMaster: BlockManagerMaster stopped
22/05/26 14:08:06 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
22/05/26 14:08:06 INFO SparkContext: Successfully stopped SparkContext

```
**What happens instead**

**Spark and TiSpark version info**

**Comment by xuanyu66** [comment]
https://bugs.mysql.com/bug.php?id=93590

**Comment by Daemonxiao** [comment]
@xuanyu66 Thanks for your reminder. It also may be related to the JDK version. I have not received warn in Oracle 1.8.0_60 OpenJDK.
