### ISSUE TITLE
Invalid Flag type for DateType: 2

### ISSUE THREAD

**Issue by Novemser** [pingcap/tispark#255]
SQL
```scala
val q1 = spark.sql(
      """select
        |   l_returnflag
        |from
        |   lineitem
        |where
        |   l_shipdate <= date '1998-12-01'
        |group by
        |   l_returnflag
      """.stripMargin)
```

Exception
```
Caused by: com.pingcap.tikv.exception.InvalidCodecFormatException: Invalid Flag type for DateType: 2
  at com.pingcap.tikv.types.AbstractDateTimeType.decodeDateTime(AbstractDateTimeType.java:39)
  at com.pingcap.tikv.types.DateType.decodeNotNull(DateType.java:48)
  at com.pingcap.tikv.types.DateType.decodeNotNull(DateType.java:26)
  at com.pingcap.tikv.types.DataType.decode(DataType.java:103)
  at com.pingcap.tikv.row.DefaultRowReader.readRow(DefaultRowReader.java:43)
  at com.pingcap.tikv.operation.iterator.CoprocessIterator$1.next(CoprocessIterator.java:76)
  at com.pingcap.tikv.operation.iterator.CoprocessIterator$1.next(CoprocessIterator.java:72)
  at org.apache.spark.sql.tispark.TiRDD$$anon$2.next(TiRDD.scala:88)
  at org.apache.spark.sql.tispark.TiRDD$$anon$2.next(TiRDD.scala:55)
  at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
  at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
  at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.agg_doAggregateWithKeys$(Unknown Source)
  at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
  at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
  at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:377)
  at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
  at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:126)
  at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
  at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
  at org.apache.spark.scheduler.Task.run(Task.scala:99)
  at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:748)

```

**Comment by Novemser** [comment]
Fixed by https://github.com/pingcap/tispark/pull/256
