### ISSUE TITLE
Region / Store related Error during TPC-H 22

### ISSUE THREAD

**Issue by ilovesoup** [pingcap/tispark#26]
Caused by: org.apache.spark.sql.catalyst.errors.package$TreeNodeException: execute, tree:
Exchange SinglePartition
+- *HashAggregate(keys=[], functions=[partial_avg(c_acctbal#65)], output=[sum#163, count#164L])
   +- *Project [c_acctbal#65]
      +- *Filter substring(c_phone#64, 1, 2) IN (20,40,22,30,39,42,21)
         +- Scan CoprocessorRDD[c_acctbal#65,c_phone#64]

  at org.apache.spark.sql.catalyst.errors.package$.attachTree(package.scala:56)
  at org.apache.spark.sql.execution.exchange.ShuffleExchange.doExecute(ShuffleExchange.scala:112)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:114)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:114)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:135)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:132)
  at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:113)
  at org.apache.spark.sql.execution.InputAdapter.inputRDDs(WholeStageCodegenExec.scala:235)
  at org.apache.spark.sql.execution.aggregate.HashAggregateExec.inputRDDs(HashAggregateExec.scala:141)
  at org.apache.spark.sql.execution.WholeStageCodegenExec.doExecute(WholeStageCodegenExec.scala:368)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:114)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:114)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:135)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:132)
  at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:113)
  at org.apache.spark.sql.execution.SparkPlan.getByteArrayRdd(SparkPlan.scala:225)
  at org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:272)
  at org.apache.spark.sql.execution.SubqueryExec$$anonfun$relationFuture$1$$anonfun$apply$4.apply(basicPhysicalOperators.scala:554)
  at org.apache.spark.sql.execution.SubqueryExec$$anonfun$relationFuture$1$$anonfun$apply$4.apply(basicPhysicalOperators.scala:551)
  at org.apache.spark.sql.execution.SQLExecution$.withExecutionId(SQLExecution.scala:94)
  at org.apache.spark.sql.execution.SubqueryExec$$anonfun$relationFuture$1.apply(basicPhysicalOperators.scala:551)
  at org.apache.spark.sql.execution.SubqueryExec$$anonfun$relationFuture$1.apply(basicPhysicalOperators.scala:551)
  at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
  at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:748)
Caused by: com.pingcap.tikv.exception.GrpcException: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNKNOWN: invalid zero store id
  at com.pingcap.tikv.region.RegionManager.getStoreById(RegionManager.java:144)
  at com.pingcap.tikv.region.RegionManager.getRegionStorePairByKey(RegionManager.java:129)
  at com.pingcap.tikv.util.RangeSplitter.splitRangeByRegion(RangeSplitter.java:125)
  at com.pingcap.tispark.TiRDD.getPartitions(TiRDD.scala:77)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
  at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
  at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
  at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
  at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
  at org.apache.spark.ShuffleDependency.<init>(Dependency.scala:91)
  at org.apache.spark.sql.execution.exchange.ShuffleExchange$.prepareShuffleDependency(ShuffleExchange.scala:261)
  at org.apache.spark.sql.execution.exchange.ShuffleExchange.prepareShuffleDependency(ShuffleExchange.scala:84)
  at org.apache.spark.sql.execution.exchange.ShuffleExchange$$anonfun$doExecute$1.apply(ShuffleExchange.scala:121)
  at org.apache.spark.sql.execution.exchange.ShuffleExchange$$anonfun$doExecute$1.apply(ShuffleExchange.scala:112)
  at org.apache.spark.sql.catalyst.errors.package$.attachTree(package.scala:52)
  ... 28 more
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNKNOWN: invalid zero store id
  at com.google.guava4pingcap.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:476)
  at com.google.guava4pingcap.util.concurrent.AbstractFuture.get(AbstractFuture.java:455)
  at com.google.guava4pingcap.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79)
  at com.pingcap.tikv.region.RegionManager.getStoreById(RegionManager.java:142)
  ... 61 more
Caused by: io.grpc.StatusRuntimeException: UNKNOWN: invalid zero store id
  at io.grpc.Status.asRuntimeException(Status.java:543)
  at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:395)
  at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
  at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:76)
  at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:512)
  at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:429)
  at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:544)
  at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
  at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:117)
  ... 3 more

Not reproducible for now. Likely due to wrong mistake of caching / error handling for region.

**Comment by ilovesoup** [comment]
Does this happen still after we fix the error handling logic?
If not, please close this. @zhexuany

**Comment by zhexuany** [comment]
@ilovesoup I believe it still happens if `TiKV` side are too busy.

**Comment by shenli** [comment]
If TiKV is too busy, you should backoff with a longer time and retry.

**Comment by zhexuany** [comment]
Yes. I plan to do it this week.

**Comment by shenli** [comment]
OK

**Comment by ilovesoup** [comment]
Backoff has been added. Please verify and close it.
@zhexuany

**Comment by zhexuany** [comment]
@ilovesoup verified. such error is still present but not fatal any more. Spark can recovery from failure. Closing.
