### ISSUE TITLE
NPE when decoding datetime

### ISSUE THREAD

**Issue by Novemser** [pingcap/tispark#262]
Schema:
```
CREATE TABLE `tmp_debug` (
  `sign_time` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

INSERT INTO `tmp_debug` VALUES ('0000-00-00 00:00:00');
```

SQL
```
SELECT * FROM tmp_debug;
```

Exception
```
Caused by: java.lang.NullPointerException
  at com.pingcap.tikv.types.DateTimeType.decodeNotNull(DateTimeType.java:55)
  at com.pingcap.tikv.types.DateTimeType.decodeNotNull(DateTimeType.java:31)
  at com.pingcap.tikv.types.DataType.decode(DataType.java:103)
  at com.pingcap.tikv.row.DefaultRowReader.readRow(DefaultRowReader.java:43)
  at com.pingcap.tikv.operation.iterator.CoprocessIterator$1.next(CoprocessIterator.java:76)
  at com.pingcap.tikv.operation.iterator.CoprocessIterator$1.next(CoprocessIterator.java:72)
  at org.apache.spark.sql.tispark.TiRDD$$anon$2.next(TiRDD.scala:88)
  at org.apache.spark.sql.tispark.TiRDD$$anon$2.next(TiRDD.scala:55)
  at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
  at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:232)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:225)
  at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:827)
  at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:827)
  at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
  at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
  at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
  at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
  at org.apache.spark.scheduler.Task.run(Task.scala:99)
  at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)

```

**Comment by Novemser** [comment]
Should be fixed by https://github.com/pingcap/tispark/pull/261
