### ISSUE TITLE
[BUG] TiSpark scan TiKV partition table crash

### ISSUE THREAD

**Issue by qumingxing** [pingcap/tispark#2773]
TiDB version：v7.5.1
TiSpark version : 3.2_2.12-3.2.2

7.5.1 TiFlash enable Storage and Compute Architecture and TiSpark scan TiKV partition table failed. none-partition tables are normal

Exception:
Caused by: com.pingcap.tikv.exception.RegionTaskException: Handle region task failed:
	at com.pingcap.tikv.operation.iterator.DAGIterator.process(DAGIterator.java:233)
	at com.pingcap.tikv.operation.iterator.DAGIterator.lambda$submitTasks$1(DAGIterator.java:91)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 3 more
Caused by: com.pingcap.tikv.exception.SelectException: [FLASH:Table:NotExists] Table doesn't exist, keyspace=4294967295 table_id=411246
	at com.pingcap.tikv.region.RegionStoreClient.doCoprocessor(RegionStoreClient.java:766)

**Comment by sunxiaoguang** [comment]
Unfortunately, Current TiSpark implementation doesn't support TiDB version greater than 6.x.
https://docs.pingcap.com/tidb/stable/tispark-overview#choose-tispark-version 

There will be a new architecture coming out to make TiSpark as thin as a simple adaptor on top of JDBC connector to make it support newer version of TiDB without extra development.
