### ISSUE TITLE
Occur exception when call tidbMapDatabase

### ISSUE THREAD

**Issue by kkfnui** [pingcap/tispark#283]
Occur exception when call `tidbMapDatabase`

### Env

- Scala: 2.11.8 
- JDK: Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_152
- TiSpark:  [tispark-0.1.0-SNAPSHOT-jar-with-dependencies.jar](http://download.pingcap.org/tispark-0.1.0-SNAPSHOT-jar-with-dependencies.jar)
- Hadoop: hadoop-2.7.5
- System: Linux 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

### Exception

```
scala> ti.tidbMapDatabase("vntopnews_push")
2018-03-15 10:38:24 WARN  General:96 - Plugin (Bundle) "org.datanucleus.store.rdbms" is already registered. Ensure you dont have multiple JAR versions of the same plugin in the classpath. The URL "file:/usr/local/spark/spark/jars/datanucleus-rdbms-3.2.9.jar" is already registered, and you are trying to register an identical plugin located at URL "file:/usr/local/spark/spark-2.3.0-bin-hadoop2.7/jars/datanucleus-rdbms-3.2.9.jar."
2018-03-15 10:38:24 WARN  General:96 - Plugin (Bundle) "org.datanucleus" is already registered. Ensure you dont have multiple JAR versions of the same plugin in the classpath. The URL "file:/usr/local/spark/spark/jars/datanucleus-core-3.2.10.jar" is already registered, and you are trying to register an identical plugin located at URL "file:/usr/local/spark/spark-2.3.0-bin-hadoop2.7/jars/datanucleus-core-3.2.10.jar."
2018-03-15 10:38:24 WARN  General:96 - Plugin (Bundle) "org.datanucleus.api.jdo" is already registered. Ensure you dont have multiple JAR versions of the same plugin in the classpath. The URL "file:/usr/local/spark/spark-2.3.0-bin-hadoop2.7/jars/datanucleus-api-jdo-3.2.6.jar" is already registered, and you are trying to register an identical plugin located at URL "file:/usr/local/spark/spark/jars/datanucleus-api-jdo-3.2.6.jar."
2018-03-15 10:38:27 WARN  ObjectStore:568 - Failed to get database global_temp, returning NoSuchObjectException
java.lang.AbstractMethodError
  at org.apache.spark.internal.Logging$class.initializeLogIfNecessary(Logging.scala:99)
  at org.apache.spark.sql.TiContext.initializeLogIfNecessary(TiContext.scala:26)
  at org.apache.spark.internal.Logging$class.log(Logging.scala:46)
  at org.apache.spark.sql.TiContext.log(TiContext.scala:26)
  at org.apache.spark.internal.Logging$class.logInfo(Logging.scala:54)
  at org.apache.spark.sql.TiContext.logInfo(TiContext.scala:26)
  at org.apache.spark.sql.TiContext$$anonfun$tidbMapDatabase$1$$anonfun$apply$1.apply(TiContext.scala:68)
  at org.apache.spark.sql.TiContext$$anonfun$tidbMapDatabase$1$$anonfun$apply$1.apply(TiContext.scala:57)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at org.apache.spark.sql.TiContext$$anonfun$tidbMapDatabase$1.apply(TiContext.scala:57)
  at org.apache.spark.sql.TiContext$$anonfun$tidbMapDatabase$1.apply(TiContext.scala:56)
  at scala.Option.foreach(Option.scala:257)
  at org.apache.spark.sql.TiContext.tidbMapDatabase(TiContext.scala:56)
  ... 49 elided
```

**Comment by ilovesoup** [comment]
Spark 2.3 is not officially supported yet (planned though). Please try 2.1.1 and see if works?
