### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by ilovesoup** [pingcap/tispark#372]
18/06/25 12:16:13 WARN channel.AbstractChannelHandlerContext: An exception 'io.netty.netty4pingcap.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 9529458983, max: 9544663040)' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
io.netty.netty4pingcap.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 9529458983, max: 9544663040)
 at io.netty.netty4pingcap.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:640)
 at io.netty.netty4pingcap.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:594)
 at io.netty.netty4pingcap.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:764)
 at io.netty.netty4pingcap.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:740)
 at io.netty.netty4pingcap.buffer.PoolArena.allocateNormal(PoolArena.java:244)
 at io.netty.netty4pingcap.buffer.PoolArena.allocate(PoolArena.java:214)
 at io.netty.netty4pingcap.buffer.PoolArena.allocate(PoolArena.java:146)
 at io.netty.netty4pingcap.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:324)
 at io.netty.netty4pingcap.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:181)
 at io.netty.netty4pingcap.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:172)
 at io.netty.netty4pingcap.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:133)
 at io.netty.netty4pingcap.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:80)
 at io.netty.netty4pingcap.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:122)
 at io.netty.netty4pingcap.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
 at io.netty.netty4pingcap.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
 at io.netty.netty4pingcap.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
 at io.netty.netty4pingcap.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
 at io.netty.netty4pingcap.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
 at io.netty.netty4pingcap.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
 at java.lang.Thread.run(Thread.java:748)

Above is captured from user site when reading a big table and write it back as parquet.
Need to track it down and likely it's a leak somewhere.

**Comment by powqabc** [comment]
@birdstorm I have encountered the same problem. Is it fixed?

**Comment by birdstorm** [comment]
@powqabc Hi, can you provide me your TiSpark version and Spark version?
