### ISSUE TITLE
tispark:sql("xxx").toDF.write.jdbc(), failed to allocate 1677721

### ISSUE THREAD

**Issue by ggslove** [pingcap/tispark#373]
Caused by: io.netty.netty4pingcap.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 1056964903, max: 1073741824)
	at io.netty.netty4pingcap.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:640)
	at io.netty.netty4pingcap.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:594)
	at io.netty.netty4pingcap.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:764)
	at io.netty.netty4pingcap.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:740)
	at io.netty.netty4pingcap.buffer.PoolArena.allocateNormal(PoolArena.java:244)
	at io.netty.netty4pingcap.buffer.PoolArena.allocate(PoolArena.java:226)
	at io.netty.netty4pingcap.buffer.PoolArena.allocate(PoolArena.java:146)
	at io.netty.netty4pingcap.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:324)
	at io.netty.netty4pingcap.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:181)
	at io.netty.netty4pingcap.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:172)
	at io.netty.netty4pingcap.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:109)
	at io.netty.netty4pingcap.handler.codec.ByteToMessageDecoder.expandCumulation(ByteToMessageDecoder.java:516)
	at io.netty.netty4pingcap.handler.codec.ByteToMessageDecoder$1.cumulate(ByteToMessageDecoder.java:88)
	at io.netty.netty4pingcap.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
	... 15 more

**Comment by birdstorm** [comment]
Hi. @ggslove. Thanks for your feedback. 

This issue will be closed since it is same with #372, we are figuring this out, and will inform you as soon as it is fixed.
