### ISSUE TITLE
tispark 与 spark thriftserver及hive联合使用的问题

### ISSUE THREAD

**Issue by louisliu318** [pingcap/tispark#378]
**环境：**
Spark-2.1.2
TiSpark 1.0 GA
TiDB-v2.1.0-alpha
**说明**
Spark既可以连接Hive又可以连接TiDB。
**问题**
1.  刚连接进去的时候，可以查看hive中的表及数据，没有问题，但是当切换到TiDB的中操作一段时间后，如果想继续连接Hive，会不定时的出现错误。错误如下：
`Error: org.apache.spark.sql.AnalysisException: org.apache.hadoop.hive.ql.metadata.HiveException: MetaException(message:Could not connect to meta store using any of the URIs provided. Most recent failure: org.apache.thrift.transport.TTransportException: GSS initiate failed
        at org.apache.thrift.transport.TSaslTransport.sendAndThrowMessage(TSaslTransport.java:232)
        at org.apache.thrift.transport.TSaslTransport.open(TSaslTransport.java:316)
        at org.apache.thrift.transport.TSaslClientTransport.open(TSaslClientTransport.java:37)
        at org.apache.hadoop.hive.thrift.client.TUGIAssumingTransport$1.run(TUGIAssumingTransport.java:52)
        at org.apache.hadoop.hive.thrift.client.TUGIAssumingTransport$1.run(TUGIAssumingTransport.java:49)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
        at org.apache.hadoop.hive.thrift.client.TUGIAssumingTransport.open(TUGIAssumingTransport.java:49)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.open(HiveMetaStoreClient.java:420)
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.reconnect(HiveMetaStoreClient.java:315)        at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:148)
        at com.sun.proxy.$Proxy44.getDatabases(Unknown Source)
        at org.apache.hadoop.hive.ql.metadata.Hive.getDatabasesByPattern(Hive.java:1251)
        at org.apache.spark.sql.hive.client.HiveClientImpl$$anonfun$listDatabases$1.apply(HiveClientImpl.scala:350)
        at org.apache.spark.sql.hive.client.HiveClientImpl$$anonfun$listDatabases$1.apply(HiveClientImpl.scala:350)
        at org.apache.spark.sql.hive.client.HiveClientImpl$$anonfun$withHiveState$1.apply(HiveClientImpl.scala:279)
        at org.apache.spark.sql.hive.client.HiveClientImpl.liftedTree1$1(HiveClientImpl.scala:226)
        at org.apache.spark.sql.hive.client.HiveClientImpl.retryLocked(HiveClientImpl.scala:225)
        at org.apache.spark.sql.hive.client.HiveClientImpl.withHiveState(HiveClientImpl.scala:268)
        at org.apache.spark.sql.hive.client.HiveClientImpl.listDatabases(HiveClientImpl.scala:349)
        at org.apache.spark.sql.hive.HiveExternalCatalog$$anonfun$listDatabases$1.apply(HiveExternalCatalog.scala:182)
        at org.apache.spark.sql.hive.HiveExternalCatalog$$anonfun$listDatabases$1.apply(HiveExternalCatalog.scala:182)
        at org.apache.spark.sql.hive.HiveExternalCatalog.withClient(HiveExternalCatalog.scala:97)
        at org.apache.spark.sql.hive.HiveExternalCatalog.listDatabases(HiveExternalCatalog.scala:181)
        at org.apache.spark.sql.catalyst.catalog.SessionCatalog.listDatabases(SessionCatalog.scala:194)        at org.apache.spark.sql.hive.TiSessionCatalog.listDatabases(TiSessionCatalog.scala:82)
        at org.apache.spark.sql.execution.command.ShowDatabasesCommand$$anonfun$2.apply(databases.scala:44)
        at org.apache.spark.sql.execution.command.ShowDatabasesCommand$$anonfun$2.apply(databases.scala:44)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.sql.execution.command.ShowDatabasesCommand.run(databases.scala:44)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:58)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:56)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:74)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:114)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:114)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:135)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:132)
        at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:113)
        at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:92)
        at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:92)
        at org.apache.spark.sql.Dataset.<init>(Dataset.scala:185)
        at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:64)
        at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:600)
        at org.apache.spark.sql.SQLContext.sql(SQLContext.scala:699)
        at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation.org$apache$spark$sql$hive$thriftserver$SparkExecuteStatementOperation$$execute(SparkExecuteStatementOperation.scala:231)
        at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$1$$anon$2.run(SparkExecuteStatementOperation.scala:174)
        at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$1$$anon$2.run(SparkExecuteStatementOperation.scala:171)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
        at org.apache.spark.sql.hive.thriftserver.SparkExecuteStatementOperation$$anon$1.run(SparkExecuteStatementOperation.scala:184)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
); (state=,code=0)
0: jdbc:hive2://jx-bd-hadoop249.zeus.lianjia.> use default;
Error: org.apache.spark.sql.AnalysisException: org.apache.hadoop.hive.ql.metadata.HiveException: java.lang.RuntimeException: Unable to instantiate org.apache.hadoop.hive.ql.metadata.SessionHiveMetaStoreClient; (state=,code=0)`

2. 在TiDB中 执行show tables 库名显示不正确，如下我在 _or_test_ 库中执行操作，显示如下：
`0: jdbc:hive2://hadoop249> show tables;
+-----------+------------+--------------+--+
| database  | tableName  | isTemporary  |
+-----------+------------+--------------+--+
| person    | person     | false        |
| a         | a          | false        |
| b         | b          | false        |
+-----------+------------+--------------+--+
3 rows selected (0.017 seconds)`
3. 当hive中的库和TiDB中的库名一样的时候，只能使用TiDB的库，不能使用Hive中的库。

**Comment by birdstorm** [comment]
I have pushed a Pull Request for second issue, see #379

**Comment by louisliu318** [comment]
Thanks for the quick reply. @birdstorm ,What about the question 1 and question 3?

**Comment by ilovesoup** [comment]
@louisliu318 for question one, can you take a look at thrift-sever's log?
for 3, for now there is no way to map using a different name in ThriftServer mode. But we can make a new configuration to allow append prefix on database name to resolve conflict. Does this sounds ok for you?

**Comment by louisliu318** [comment]
@ilovesoup for question 3,  appending prefix on database name is a good way to go. Forquestion 1, I reproduce it ---{ the problem occurs if I don't issue any query through beeline client for a while, maybe 3~5 minutes }. According to spark thriftserver log, it seems hive metastore client disconnected due to kerberos. Below is part of my thriftserver log:
[spark-thriftserver.log](https://github.com/pingcap/tispark/files/2158892/spark-thriftserver.log)

**Comment by ilovesoup** [comment]
Kerberos is kind of fragile and a trouble itself. Essentially we only hooked on Spark native thriftserver with meta data injection and touched nothing about communication and security. The code 99.99% the same as native thriftserver.
Would you make sure you go through normal procedure of Spark native thriftserver kerberos setup first? @louisliu318 

For what I can suggest, you might add "-Dsun.security.krb5.debug=true" to tithrift-server startup script and check what's really going wrong.

**Comment by louisliu318** [comment]
@ilovesoup ,yes, it our own setting problem, not a tispark issue. Thank for your flying reply.
