### ISSUE TITLE
使用spark-shell在初始化连接时pd连不上

### ISSUE THREAD

**Issue by Mingdr** [pingcap/tispark#398]
按照官方的文档进行调试的，https://pingcap.com/docs-cn/tispark/tispark-user-guide/。
系统：centos 7 
tidb：正常
spark_master，spark_slave：均正常启动，能运行官方测试。
用户：root
运行：
[root@localhost spark]# ./bin/spark-shell
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/tdata/tidata/spark/jars/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/tdata/tidata/spark/jars/tispark-SNAPSHOT-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
18/07/19 16:22:41 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
18/07/19 16:22:41 WARN Utils: Your hostname, localhost.localdomain resolves to a loopback address: 127.0.0.1; using 192.168.0.222 instead (on interface ens33)
18/07/19 16:22:41 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
18/07/19 16:22:45 WARN ObjectStore: Failed to get database global_temp, returning NoSuchObjectException
Spark context Web UI available at http://192.168.0.222:4040
Spark context available as 'sc' (master = spark://192.168.0.222:7077, app id = app-20180719162242-0002).
Spark session available as 'spark'.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.1.1
      /_/
Using Scala version 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_162)
Type in expressions to have them evaluated.
Type :help for more information.
-----------------------------------------------------------------
scala> import org.apache.spark.sql.TiContext
import org.apache.spark.sql.TiContext
-----------------------------------------------------------------
scala> val ti = new TiContext(spark)
18/07/19 16:24:03 WARN PDClient: failed to get member from pd server.
io.grpc.StatusRuntimeException: UNAVAILABLE
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:210)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:191)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:124)
        at com.pingcap.tikv.kvproto.PDGrpc$PDBlockingStub.getMembers(PDGrpc.java:694)
        at com.pingcap.tikv.PDClient.getMembers(PDClient.java:223)
        at com.pingcap.tikv.PDClient.initCluster(PDClient.java:306)
        at com.pingcap.tikv.PDClient.createRaw(PDClient.java:325)
        at com.pingcap.tikv.TiSession.getPDClient(TiSession.java:71)
        at com.pingcap.tikv.TiSession.getTimestamp(TiSession.java:55)
        at com.pingcap.tikv.TiSession.createSnapshot(TiSession.java:59)
        at com.pingcap.tikv.TiSession.lambda$getCatalog$0(TiSession.java:84)
        at com.pingcap.tikv.catalog.Catalog.<init>(Catalog.java:113)
        at com.pingcap.tikv.TiSession.getCatalog(TiSession.java:86)
        at org.apache.spark.sql.TiContext.<init>(TiContext.scala:38)
        at $line15.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:24)
        at $line15.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:29)
        at $line15.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:31)
        at $line15.$read$$iw$$iw$$iw$$iw$$iw.<init>(<console>:33)
        at $line15.$read$$iw$$iw$$iw$$iw.<init>(<console>:35)
        at $line15.$read$$iw$$iw$$iw.<init>(<console>:37)
        at $line15.$read$$iw$$iw.<init>(<console>:39)
        at $line15.$read$$iw.<init>(<console>:41)
        at $line15.$read.<init>(<console>:43)
        at $line15.$read$.<init>(<console>:47)
        at $line15.$read$.<clinit>(<console>)
        at $line15.$eval$.$print$lzycompute(<console>:7)
        at $line15.$eval$.$print(<console>:6)
        at $line15.$eval.$print(<console>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:786)
        at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1047)
        at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:638)
        at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:637)
        at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
        at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
        at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:637)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:569)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:565)
        at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:807)
        at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:681)
        at scala.tools.nsc.interpreter.ILoop.processLine(ILoop.scala:395)
        at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:415)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:923)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:909)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:909)
        at scala.reflect.internal.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:97)
        at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:909)
        at org.apache.spark.repl.Main$.doMain(Main.scala:69)
        at org.apache.spark.repl.Main$.main(Main.scala:52)
        at org.apache.spark.repl.Main.main(Main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:743)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: io.netty.netty4pingcap.channel.ConnectTimeoutException: connection timed out: /192.168.1.210:2379
        at io.netty.netty4pingcap.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:267)
        at io.netty.netty4pingcap.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
        at io.netty.netty4pingcap.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:120)
        at io.netty.netty4pingcap.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.netty4pingcap.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.netty4pingcap.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
        at io.netty.netty4pingcap.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.netty4pingcap.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:748)
----------------------------------------------------------
这就卡住了，spark-default.conf 文件详情：
![8sqi797j z s kwqsmg o k](https://user-images.githubusercontent.com/16832088/42931002-1c0f4332-8b71-11e8-88ba-318c6159bfa4.png)

---------------------------------------------------------
192.168.1.210:2379 pd节点能使用pd-ctl 进行访问。

#求助，实在不知道怎么做。

**Comment by birdstorm** [comment]
Would you please print the result of `println(spark.conf.getAll)`?

**Comment by Mingdr** [comment]
scala> println(spark.conf.getAll)
Map(spark.driver.host -> 192.168.0.222, spark.driver.port -> 36943, hive.metastore.warehouse.dir -> file:/tdata/tidata/spark/spark-warehouse/, spark.repl.class.uri -> spark://192.168.0.222:36943/classes, spark.jars -> , spark.repl.class.outputDir -> /tmp/spark-f25f5ed0-76ea-499f-971b-20fbeb70983c/repl-d242f632-48bf-49fa-95f1-076b0937a3a8, spark.app.name -> Spark shell, spark.tispark.pd.addresses -> 192.168.1.210:2379, spark.executor.id -> driver, spark.submit.deployMode -> client, spark.master -> local[*], spark.home -> /tdata/tidata/spark, spark.sql.catalogImplementation -> hive, spark.app.id -> local-1531990650861)
@birdstorm

**Comment by Mingdr** [comment]
Any questions about that ？

**Comment by birdstorm** [comment]
@Mingdr Just collecting useful information so that I could reproduce it. Thanks!

**Comment by birdstorm** [comment]
@Mingdr  能确定你的spark driver节点能连上pd server吗？

**Comment by Mingdr** [comment]
怎么确定是不是连得上呢

**Comment by Mingdr** [comment]
不知道怎么用spark driver 连接pd server @birdstorm

**Comment by birdstorm** [comment]
@Mingdr 在spark driver节点上使用pd-ctl 看看？

**Comment by Mingdr** [comment]
![1](https://user-images.githubusercontent.com/16832088/42979303-0f6b68a2-8c04-11e8-9a1c-5e2c908c1f28.png)
@birdstorm

**Comment by ilovesoup** [comment]
spark.driver.host -> 192.168.0.222
spark.tispark.pd.addresses -> 192.168.1.210:2379
这两个是同一个机器？

**Comment by Mingdr** [comment]
我在222节点后210节点都执行了pd-ctl了，都没问题。
我在222节点执行：
[root@localhost spark]# nmap -p 2000-9000 192.168.0.210

Starting Nmap 6.40 ( http://nmap.org ) at 2018-07-20 16:40 CST
Nmap scan report for 192.168.0.210
Host is up (0.00066s latency).
Not shown: 6997 closed ports
PORT     STATE SERVICE
2379/tcp open  unknown
2380/tcp open  unknown
8123/tcp open  polipo
9000/tcp open  cslistener
MAC Address: 50:9A:4C:61:7D:EE (Unknown)

**Comment by Mingdr** [comment]
我好像知道问题了。。。我写错了ip。。 耽误大佬们时间了 @birdstorm  @ilovesoup
