### ISSUE TITLE
how to configure & use  TiSpark's SQL Interactive shell

### ISSUE THREAD

**Issue by luyee** [pingcap/tispark#51]
now spark-shell  is ok 

howerer ,tispark-sql,

when run : bin/tispark-sql
tispark-sql> select count (*) from tidb;
17/10/11 10:56:56 INFO SparkSqlParser: Parsing command: select count (*) from tidb
17/10/11 10:56:57 WARN PDClient: failed to get member from pd server.
io.grpc.StatusRuntimeException: UNAVAILABLE: Transport closed for unknown reason
        at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227)
        at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)
        at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
        at com.pingcap.tikv.kvproto.PDGrpc$PDBlockingStub.getMembers(PDGrp

how to configure

**Comment by luyee** [comment]
add  
`spark.tispark.pd.addresses
`
to  conf/spark-defaults.conf  is  ok



--

**Comment by ilovesoup** [comment]
yes. Latest change for TiSpark has added some conf item which is addressed here
https://github.com/pingcap/tispark#configuration

**Comment by luyee** [comment]
add  
`spark.tispark.pd.addresses
`
to  conf/spark-defaults.conf  seems ok



--
