### ISSUE TITLE
noSuchMethodError when use count in tispark

### ISSUE THREAD

**Issue by Mvpanswer7** [pingcap/tispark#515]
`java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.expressions.Alias$.apply$default$6(Lorg/apache/spark/sql/catalyst/expressions/Expression;Ljava/lang/String;)Ljava/lang/Boolean;`
sparksql: `select count(*) from tidb_table`

**Comment by birdstorm** [comment]
Hi, @Mvpanswer7  which Spark version are you using?

**Comment by Mvpanswer7** [comment]
Full stacktrace:
`java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.expressions.Alias$.apply$default$6(Lorg/apache/spark/sql/catalyst/expressions/Expression;Ljava/lang/String;)Ljava/lang/Boolean;
	at org.apache.spark.sql.TiStrategy$$anonfun$3.applyOrElse(TiStrategy.scala:394)
	at org.apache.spark.sql.TiStrategy$$anonfun$3.applyOrElse(TiStrategy.scala:393)
	at scala.PartialFunction$$anonfun$runWith$1.apply(PartialFunction.scala:141)
	at scala.PartialFunction$$anonfun$runWith$1.apply(PartialFunction.scala:140)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.collect(TraversableLike.scala:271)
	at scala.collection.immutable.List.collect(List.scala:315)
	at org.apache.spark.sql.TiStrategy.groupAggregateProjection(TiStrategy.scala:393)
	at org.apache.spark.sql.TiStrategy.org$apache$spark$sql$TiStrategy$$doPlan(TiStrategy.scala:527)
	at org.apache.spark.sql.TiStrategy$$anonfun$apply$1.applyOrElse(TiStrategy.scala:101)
	at org.apache.spark.sql.TiStrategy$$anonfun$apply$1.applyOrElse(TiStrategy.scala:99)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:223)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:219)`

**Comment by Mvpanswer7** [comment]
I am not building, I am using your release tispark-core-1.1-SNAPSHOT-jar-with-dependencies.jar

**Comment by Mvpanswer7** [comment]
@birdstorm Hi, I am using spark 2.3.0

**Comment by Mvpanswer7** [comment]
我直接用的你们的release的jar包，我需要自己重新编译一个支持2.3的jar包么？

**Comment by birdstorm** [comment]
Oh, TiSpark 1.1 is not compatible with Spark 2.3, you will have to use Spark 2.1 instead.

If you want to use Spark 2.3, you should build from source using master branch.

The version compatible information is also available in [README.md](https://github.com/pingcap/tispark)

**Comment by Mvpanswer7** [comment]
@birdstorm  Hi, I build a jar named `tispark-core-2.0-SNAPSHOT-jar-with-dependencies.jar` and use it in spark 2.3.0, but get a new exception: `java.lang.AssertionError: assertion failed: No plan for Relation[id#76,hash#77,imei#78,imei_hash#79,package_name#80] TiDBRelation(com.pingcap.tikv.TiSession@23da0650,TiTableReference(tables,cc,9223372036854775807),com.pingcap.tispark.MetaManager@e5fe73c)`

**Comment by Mvpanswer7** [comment]
I tested in spark2.3.0 with tispark-core-1.1-SNAPSHOT-jar-with-dependencies.jar, I can do query like `select *` and `select columns`, only throws error when I query `select count()`

**Comment by Mvpanswer7** [comment]
@birdstorm  I built a `tispark-core-2.0-SNAPSHOT-jar-with-dependencies.jar` from master branch, and set my pdserver in spark conf, but spark application failed  on start.Error message below:
![image](https://user-images.githubusercontent.com/5041016/49494316-3d2fe080-f89a-11e8-8d57-bb79fe693421.png)
my tidb version:
![image](https://user-images.githubusercontent.com/5041016/49494417-913ac500-f89a-11e8-9479-874ef6f570ec.png)

**Comment by birdstorm** [comment]
Have you specified pd addresses in `$SPARK_HOME/conf/spark-defaults.conf`? You can start from reading the [document](https://github.com/pingcap/tispark/blob/master/docs/userguide.md) first.

**Comment by Mvpanswer7** [comment]
@birdstorm Hi, I specified like this:
`spark-submit \
...\
 --conf spark.tispark.pd.addresses=192.168.8.16:9019 ` 
in my `spark-submit` shell, I think the way I specify pd server is correct, because I have been using it all the way till yesterday

**Comment by birdstorm** [comment]
I see, did you introduce any other dependencies that may include incompatible GRPC versions?

**Comment by Mvpanswer7** [comment]
I used 2 jars that need to new Context like TiContext in my project, one is tispark, the other is carbonData, I will check it

**Comment by birdstorm** [comment]
Great! You can use `mvn dependency:tree` or `jar tf xxxx.jar` to ensure your dependencies are compatible with your TiSpark version. TiSpark has already shaded the grpc dependencies as `shade.io.grpc` and you may simply use it in your project.

**Comment by Mvpanswer7** [comment]
@birdstorm  Hi, here is my situation right now:
I wrote a raw test to regenerate the problem I faced yesterday, code as follows, running in spark2.3.0 with `tispark-core-1.1-SNAPSHOT-jar-with-dependencies.jar`:
`  def main(args: Array[String]) = {`
  `  val ss = SparkSession`
      `.builder()`
      `.master("local[*]")`
   `   .config("spark.tispark.pd.addresses","192.168.8.16: 9019")`
 `     .getOrCreate()`
`    val tiContext = new TiContext(ss)`
`    tiContext.conf.set("spark.tispark.request.timezone.offset", "-800")`
 `   val table =  tiContext.tidbMapTable("insight_sources", "cc")`
`    val t1 = ss.sql("select * from cc limit 1")`
`    //val t1 = ss.sql("select count(*) from cc ")`
 `   t1.show()`
`  }`
Above code work fine, also works with other select situations. Only when I use `count` in my sql, the program will throw exception `Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.expressions.Alias$.apply$default$6(Lorg/apache/spark/sql/catalyst/expressions/Expression;Ljava/lang/String;)Ljava/lang/Boolean;
	at org.apache.spark.sql.TiStrategy$$anonfun$3.applyOrElse(TiStrategy.scala:394)
	at org.apache.spark.sql.TiStrategy$$anonfun$3.applyOrElse(TiStrategy.scala:393)`
If I change `tispark-core-1.1-SNAPSHOT-jar-with-dependencies.jar` to `tispark-core-2.0-SNAPSHOT-jar-with-dependencies.jar` , the program will throw exception even when I query `select * from cc limit 1`, exception is
 `Exception in thread "main" java.lang.AssertionError: assertion failed: No plan for Relation[device_id#0,hash#1,imei#2,imei_hash#3,package_name#4] TiDBRelation(com.pingcap.tikv.TiSession@134abd78,TiTableReference(insight_sources,cc,9223372036854775807),com.pingcap.tispark.MetaManager@3b0ed98a)

	at scala.Predef$.assert(Predef.scala:170)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2$$anonfun$apply$2.apply(QueryPlanner.scala:78)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2$$anonfun$apply$2.apply(QueryPlanner.scala:75)`

**Comment by birdstorm** [comment]
I think I can highlight those FAQs in ReadMe(although these requirements already has been bolded). Does it help solve your problem? @Mvpanswer7

**Comment by Mvpanswer7** [comment]
@birdstorm  Hi, yes, it solved my problem, I add `config("spark.sql.extensions", "org.apache.spark.sql.TiExtensions")` in my code, and `tispark-core-2.0-SNAPSHOT-jar-with-dependencies.jar` works fine now, thanks a lot!

**Comment by birdstorm** [comment]
Glad to hear that! May I close the issue?

**Comment by Mvpanswer7** [comment]
OK, you can close it. Thanks
