### ISSUE TITLE
Java客户端连接tispark报错: tco count should be positive

### ISSUE THREAD

**Issue by ericisme** [pingcap/tispark#558]
java 项目里使用 ：
  	<dependency>
		<groupId>org.apache.spark</groupId>
		<artifactId>spark-sql_2.11</artifactId>
		<version>2.3.2</version>
	</dependency>
  
      <dependency>
      <groupId>com.pingcap.tispark</groupId>
      <artifactId>tispark-core</artifactId>
      <version>1.1</version>
    </dependency>
    <dependency>
      <groupId>com.pingcap.tikv</groupId>
      <artifactId>tikv-client</artifactId>
      <version>1.1</version>
    </dependency>

连接tispark,
public class Test {

	public static void main(String[] args) {
		//https://blog.csdn.net/tianshuai1212/article/details/82343540
		SparkSession sparkSession = SparkSession
                .builder()
                //.config("spark.port.maxRetries", "10000000")
                //.config("spark.testing.memory", "2147480000")
                .config("spark.driver.host", "tieclipse")
                //.config("spark.blockManager.port", "44105")
                .config("spark.driver.port","4405")
                .config("spark.tispark.backoffer.maxSleep", "500000ms")
                .config("spark.driver.memory", "2g")
                .config("spark.tispark.grpc.timeout_in_sec", 100)
                .config("spark.tispark.meta.reload_period_in_sec", 60)
                .config("spark.tispark.pd.addresses", "192.168.9.119:2379,192.168.9.59:2379,192.168.9.107:2379")
                .master("spark://192.168.9.119:7077")
                .appName("test tispark")
                .getOrCreate();

			TiContext tiContext =  new TiContext(sparkSession);

			tiContext.tidbMapDatabase("erp959", false);
			//sparkSession.sql("SELECT count(1) FROM erp959.order_order").show();
			
			/*Properties connectionProperties = new Properties();
	        connectionProperties.put("user", "root");
	        connectionProperties.put("password", "");
	        
			
			Dataset<Row> dataset = tiContext.session().read().jdbc("jdbc:mysql://192.168.9.119:3326/erp959", "order_order", connectionProperties);
			dataset.show();*/
			sparkSession.newSession().sql("SELECT count(1) FROM erp959.order_order").show();	
	}

}

启动报错:
19/01/22 09:14:51 WARN ConcreteBackOffer: backoffer.maxSleep 5000ms is exceeded, errors:
2.shade.io.grpc.StatusRuntimeException: UNKNOWN: tso count should be positive
3.shade.io.grpc.StatusRuntimeException: UNKNOWN: tso count should be positive
4.shade.io.grpc.StatusRuntimeException: UNKNOWN: tso count should be positive
Exception in thread "main" com.pingcap.tikv.exception.GrpcException: retry is exhausted.
	at com.pingcap.tikv.util.ConcreteBackOffer.doBackOff(ConcreteBackOffer.java:124)
	at com.pingcap.tikv.operation.PDErrorHandler.handleRequestError(PDErrorHandler.java:54)
	at com.pingcap.tikv.policy.RetryPolicy.callWithRetry(RetryPolicy.java:59)
	at com.pingcap.tikv.AbstractGRPCClient.callWithRetry(AbstractGRPCClient.java:65)
	at com.pingcap.tikv.PDClient.getTimestamp(PDClient.java:75)
	at com.pingcap.tikv.TiSession.getTimestamp(TiSession.java:56)
	at com.pingcap.tikv.TiSession.createSnapshot(TiSession.java:60)
	at com.pingcap.tikv.TiSession.lambda$getCatalog$0(TiSession.java:85)
	at com.pingcap.tikv.catalog.Catalog.<init>(Catalog.java:135)
	at com.pingcap.tikv.TiSession.getCatalog(TiSession.java:89)
	at org.apache.spark.sql.TiContext.<init>(TiContext.scala:38)
	at com.edazeone.tispark.Test.main(Test.java:31)
Caused by: shade.io.grpc.StatusRuntimeException: UNKNOWN: tso count should be positive
	at shade.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:210)
	at shade.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:191)
	at shade.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:124)
	at com.pingcap.tikv.AbstractGRPCClient.lambda$callWithRetry$0(AbstractGRPCClient.java:68)
	at com.pingcap.tikv.policy.RetryPolicy.callWithRetry(RetryPolicy.java:55)
	... 9 more

ti-worker 日志(stdout )：

  2019-01-22 08:59:55 INFO  CoarseGrainedExecutorBackend:2612 - Started daemon with process name: 215@localhost
2019-01-22 08:59:55 INFO  SignalUtils:54 - Registered signal handler for TERM
2019-01-22 08:59:55 INFO  SignalUtils:54 - Registered signal handler for HUP
2019-01-22 08:59:55 INFO  SignalUtils:54 - Registered signal handler for INT
2019-01-22 08:59:56 WARN  Utils:66 - Your hostname, localhost resolves to a loopback address: 127.0.0.1; using 172.17.0.7 instead (on interface eth0)
2019-01-22 08:59:56 WARN  Utils:66 - Set SPARK_LOCAL_IP if you need to bind to another address
2019-01-22 08:59:56 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2019-01-22 08:59:56 INFO  SecurityManager:54 - Changing view acls to: root,Administrator
2019-01-22 08:59:56 INFO  SecurityManager:54 - Changing modify acls to: root,Administrator
2019-01-22 08:59:56 INFO  SecurityManager:54 - Changing view acls groups to: 
2019-01-22 08:59:56 INFO  SecurityManager:54 - Changing modify acls groups to: 
2019-01-22 08:59:56 INFO  SecurityManager:54 - SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(root, Administrator); groups with view permissions: Set(); users  with modify permissions: Set(root, Administrator); groups with modify permissions: Set()
2019-01-22 08:59:57 INFO  TransportClientFactory:267 - Successfully created connection to tieclipse/192.168.9.119:4405 after 108 ms (0 ms spent in bootstraps)
2019-01-22 08:59:57 INFO  SecurityManager:54 - Changing view acls to: root,Administrator
2019-01-22 08:59:57 INFO  SecurityManager:54 - Changing modify acls to: root,Administrator
2019-01-22 08:59:57 INFO  SecurityManager:54 - Changing view acls groups to: 
2019-01-22 08:59:57 INFO  SecurityManager:54 - Changing modify acls groups to: 
2019-01-22 08:59:57 INFO  SecurityManager:54 - SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(root, Administrator); groups with view permissions: Set(); users  with modify permissions: Set(root, Administrator); groups with modify permissions: Set()
2019-01-22 08:59:57 INFO  TransportClientFactory:267 - Successfully created connection to tieclipse/192.168.9.119:4405 after 11 ms (0 ms spent in bootstraps)
2019-01-22 08:59:57 INFO  DiskBlockManager:54 - Created local directory at /tmp/spark-2ae2132d-9b3d-4c05-b979-a25be7662b1a/executor-f79fad00-8749-4123-835d-e3ab53ba9afb/blockmgr-1f08e97a-9111-43dd-bd0e-7285e9633b8a
2019-01-22 08:59:57 INFO  MemoryStore:54 - MemoryStore started with capacity 366.3 MB
2019-01-22 08:59:57 INFO  CoarseGrainedExecutorBackend:54 - Connecting to driver: spark://CoarseGrainedScheduler@tieclipse:4405
2019-01-22 08:59:57 INFO  WorkerWatcher:54 - Connecting to worker spark://Worker@tisparkslave0:44105
2019-01-22 08:59:57 INFO  TransportClientFactory:267 - Successfully created connection to tisparkslave0/127.0.0.1:44105 after 7 ms (0 ms spent in bootstraps)
2019-01-22 08:59:57 INFO  WorkerWatcher:54 - Successfully connected to spark://Worker@tisparkslave0:44105
2019-01-22 08:59:57 INFO  CoarseGrainedExecutorBackend:54 - Successfully registered with driver
2019-01-22 08:59:57 INFO  Executor:54 - Starting executor ID 0 on host tisparkslave0
2019-01-22 08:59:58 INFO  Utils:54 - Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 6018.
2019-01-22 08:59:58 INFO  NettyBlockTransferService:54 - Server created on tisparkslave0:6018
2019-01-22 08:59:58 INFO  BlockManager:54 - Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
2019-01-22 08:59:58 INFO  BlockManagerMaster:54 - Registering BlockManager BlockManagerId(0, tisparkslave0, 6018, None)
2019-01-22 08:59:58 INFO  BlockManagerMaster:54 - Registered BlockManager BlockManagerId(0, tisparkslave0, 6018, None)
2019-01-22 08:59:58 INFO  BlockManager:54 - Initialized BlockManager: BlockManagerId(0, tisparkslave0, 6018, None)
2019-01-22 09:00:06 INFO  CoarseGrainedExecutorBackend:54 - Driver commanded a shutdown
2019-01-22 09:00:06 ERROR CoarseGrainedExecutorBackend:43 - RECEIVED SIGNAL TERM
utdown

ti-worker 日志(stderr)：

Top of Log
Spark Executor Command: "/opt/jdk/bin/java" "-cp" "/opt/spark/conf/:/opt/spark/jars/*" "-Xmx1024M" "-Dspark.blockManager.port=6018" "-Dspark.driver.port=4405" "org.apache.spark.executor.CoarseGrainedExecutorBackend" "--driver-url" "spark://CoarseGrainedScheduler@tieclipse:4405" "--executor-id" "0" "--hostname" "tisparkslave0" "--cores" "3" "--app-id" "app-20190122085954-0050" "--worker-url" "spark://Worker@tisparkslave0:44105"
========================================

tispark启动脚本：

tisparkmaster (192.168.9.119)

docker run -d --name tisparkmaster ^
  -p 7077:7077 ^
  -p 8080:8080 ^
  -v F:\tidb\spark-defaults.conf:/opt/spark/conf/spark-defaults.conf:ro ^
  -v F:\tidb\timaster\hosts:/etc/hosts ^
  -h tisparkmaster ^
  -e SPARK_MASTER_PORT=7077 ^
  -e SPARK_MASTER_WEBUI_PORT=8080 ^
  -e SPARK_PUBLIC_DNS="tisparkmaster" ^
  pingcap/tispark:latest /opt/spark/sbin/start-master.sh

tisparkslave0 (192.168.9.119)

docker run -d --name tisparkslave0 ^
  -p 38081:38081 ^
  -p 44105:44105 ^
  -v F:\tidb\spark-defaults.conf:/opt/spark/conf/spark-defaults.conf:ro ^
  -v F:\tidb\tisparkslave0\hosts:/etc/hosts ^
  -h tisparkslave0 ^
  -e SPARK_WORKER_WEBUI_PORT=38081 ^
  -e SPARK_WORKER_PORT=44105 ^
  -e SPARK_PUBLIC_DNS="tisparkslave0" ^
  pingcap/tispark:latest /opt/spark/sbin/start-slave.sh spark://tisparkmaster:7077 -h tisparkslave0

/etc/hosts (tisparkmaster):

127.0.0.1	localhost
127.0.0.1 tisparkmaster
192.168.9.119 tisparkslave0
192.168.9.59  tisparkslave1
192.168.9.107 tisparkslave2
192.168.9.119 tieclipse

/etc/hosts (tisparkslave0):

127.0.0.1	localhost
192.168.9.119 tisparkmaster
127.0.0.1 tisparkslave0
192.168.9.59  tisparkslave1
192.168.9.107 tisparkslave2
192.168.9.119 tieclipse

spark-defaults.conf:

spark.tispark.pd.addresses 192.168.29.119:2379
spark.sql.extensions org.apache.spark.sql.TiExtensions

搞了两天，一直搞不明白是什么问题 ，

**Comment by birdstorm** [comment]
@ericisme 

不好意思，这个问题是由于 1.1 版本的 TiSpark 和最新的 PD 不兼容导致的。目前有这几种办法可以解决：

1. 使用 master 版本的 TiSpark
2. 使用最新的 docker 镜像，我目前正在更新中，预计明天可以在 docker 上发布
3. 降级 PD 版本至 v2.0.5 以前

另外 master 版本的 TiSpark 还未在 maven 上发布，目前可以尝试手动编译，具体方法可见 [此文档](https://github.com/pingcap/tispark#how-to-build-from-sources)。带来不便敬请谅解。

docker 更新完毕后，我会在这个 issue 里 ping 你，可以么？

**Comment by ericisme** [comment]
好的，太感谢你了，我这就去试， “docker 更新完毕后，我会在这个 issue 里 ping 你，可以么？”， 好的，谢谢你

**Comment by ericisme** [comment]
> @ericisme
> 
> 不好意思，这个问题是由于 1.1 版本的 TiSpark 和最新的 PD 不兼容导致的。目前有这几种办法可以解决：
> 
> 1. 使用 master 版本的 TiSpark
> 2. 使用最新的 docker 镜像，我目前正在更新中，预计明天可以在 docker 上发布
> 3. 降级 PD 版本至 v2.0.5 以前
> 
> 另外 master 版本的 TiSpark 还未在 maven 上发布，目前可以尝试手动编译，具体方法可见 [此文档](https://github.com/pingcap/tispark#how-to-build-from-sources)。带来不便敬请谅解。
> 
> docker 更新完毕后，我会在这个 issue 里 ping 你，可以么？

感谢， 请问一下，使用最新版的docker镜像，指得是那个镜像？ pingcap/pd吗？ 还是pingcap/tispark？还是全套更新？

**Comment by birdstorm** [comment]
@ericisme Hi, the image has been updated.

**Comment by ericisme** [comment]
@birdstorm  另外我想问下一下那些docker的tag版本：
比如：
v2.1.3 50 MB
Last update: 3 days ago
beta 95 MB
Last update: 13 days ago
v2.0.11-binlog 43 MB
Last update: a month ago
v2.0.11 43 MB
Last update: a month ago
v2.0.10-binlog 43 MB
Last update: a month ago
v2.1.2 47 MB
Last update: a month ago
v2.0.10 43 MB
Last update: a month ago
v2.1.1 47 MB
Last update: 2 months ago
v2.1.0 47 MB
Last update: 2 months ago
v2.0.9 43 MB
Last update: 2 months ago
v2.1.0-rc.5 47 MB
Last update: 3 months ago


像v2.1.3， 这样的版本是正式发布版本吗？还是beta版，  是不是只有-rc结尾的版本才是稳定的发行版？

**Comment by birdstorm** [comment]
@ericisme  v2.1.3 是正式发布版本，rc 为候选版本，如果没有更新即可发布为正式版
