### ISSUE TITLE
Error doing database mapping

### ISSUE THREAD

**Issue by Novemser** [pingcap/tispark#58]
We may encounter an ```com.fasterxml.jackson.core.JsonParseException``` exception if we defined a ```LongText``` column in our table. Full stack trace:
```
com.pingcap.tikv.exception.TiClientInternalException: Invalid JSON value for Type TiTableInfo: {"id":148,"name":{"O":"full_data_type_table","L":"full_data_type_table"},"charset":"","collate":"","cols":[{"id":1,"name":{"O":"id_dt","L":"id_dt"},"offset":0,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":3,"Flag":4227,"Flen":11,"Decimal":0,"Charset":"binary","Collate":"binary","Elems":null},"state":5,"comment":""},{"id":2,"name":{"O":"tp_varchar","L":"tp_varchar"},"offset":1,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":15,"Flag":0,"Flen":45,"Decimal":0,"Charset":"utf8","Collate":"utf8_bin","Elems":null},"state":5,"comment":""},{"id":3,"name":{"O":"tp_datetime","L":"tp_datetime"},"offset":2,"origin_default":null,"default":"CURRENT_TIMESTAMP","generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":12,"Flag":128,"Flen":19,"Decimal":0,"Charset":"binary","Collate":"binary","Elems":null},"state":5,"comment":""},{"id":4,"name":{"O":"tp_blob","L":"tp_blob"},"offset":3,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":252,"Flag":128,"Flen":65535,"Decimal":0,"Charset":"binary","Collate":"binary","Elems":null},"state":5,"comment":""},{"id":5,"name":{"O":"tp_binary","L":"tp_binary"},"offset":4,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":254,"Flag":128,"Flen":2,"Decimal":0,"Charset":"binary","Collate":"binary","Elems":null},"state":5,"comment":""},{"id":6,"name":{"O":"tp_date","L":"tp_date"},"offset":5,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":10,"Flag":128,"Flen":10,"Decimal":0,"Charset":"binary","Collate":"binary","Elems":null},"state":5,"comment":""},{"id":7,"name":{"O":"tp_timestamp","L":"tp_timestamp"},"offset":6,"origin_default":null,"default":"CURRENT_TIMESTAMP","generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":7,"Flag":1152,"Flen":19,"Decimal":0,"Charset":"binary","Collate":"binary","Elems":null},"state":5,"comment":""},{"id":8,"name":{"O":"tp_year","L":"tp_year"},"offset":7,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":13,"Flag":128,"Flen":4,"Decimal":0,"Charset":"binary","Collate":"binary","Elems":null},"state":5,"comment":""},{"id":9,"name":{"O":"tp_bigint","L":"tp_bigint"},"offset":8,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":8,"Flag":128,"Flen":20,"Decimal":0,"Charset":"binary","Collate":"binary","Elems":null},"state":5,"comment":""},{"id":10,"name":{"O":"tp_decimal","L":"tp_decimal"},"offset":9,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":246,"Flag":128,"Flen":11,"Decimal":0,"Charset":"binary","Collate":"binary","Elems":null},"state":5,"comment":""},{"id":11,"name":{"O":"tp_double","L":"tp_double"},"offset":10,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":5,"Flag":128,"Flen":22,"Decimal":-1,"Charset":"binary","Collate":"binary","Elems":null},"state":5,"comment":""},{"id":12,"name":{"O":"tp_float","L":"tp_float"},"offset":11,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":4,"Flag":128,"Flen":12,"Decimal":-1,"Charset":"binary","Collate":"binary","Elems":null},"state":5,"comment":""},{"id":13,"name":{"O":"tp_int","L":"tp_int"},"offset":12,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":3,"Flag":128,"Flen":11,"Decimal":0,"Charset":"binary","Collate":"binary","Elems":null},"state":5,"comment":""},{"id":14,"name":{"O":"tp_mediumint","L":"tp_mediumint"},"offset":13,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":9,"Flag":128,"Flen":9,"Decimal":0,"Charset":"binary","Collate":"binary","Elems":null},"state":5,"comment":""},{"id":15,"name":{"O":"tp_real","L":"tp_real"},"offset":14,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":5,"Flag":128,"Flen":22,"Decimal":-1,"Charset":"binary","Collate":"binary","Elems":null},"state":5,"comment":""},{"id":16,"name":{"O":"tp_smallint","L":"tp_smallint"},"offset":15,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":2,"Flag":128,"Flen":6,"Decimal":0,"Charset":"binary","Collate":"binary","Elems":null},"state":5,"comment":""},{"id":17,"name":{"O":"tp_tinyint","L":"tp_tinyint"},"offset":16,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":1,"Flag":128,"Flen":4,"Decimal":0,"Charset":"binary","Collate":"binary","Elems":null},"state":5,"comment":""},{"id":18,"name":{"O":"tp_char","L":"tp_char"},"offset":17,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":254,"Flag":0,"Flen":10,"Decimal":0,"Charset":"utf8","Collate":"utf8_bin","Elems":null},"state":5,"comment":""},{"id":19,"name":{"O":"tp_nvarchar","L":"tp_nvarchar"},"offset":18,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":15,"Flag":0,"Flen":40,"Decimal":0,"Charset":"utf8","Collate":"utf8_bin","Elems":null},"state":5,"comment":""},{"id":20,"name":{"O":"tp_longtext","L":"tp_longtext"},"offset":19,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":251,"Flag":0,"Flen":4294967295,"Decimal":0,"Charset":"utf8","Collate":"utf8_bin","Elems":null},"state":5,"comment":""},{"id":21,"name":{"O":"tp_mediumtext","L":"tp_mediumtext"},"offset":20,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":250,"Flag":0,"Flen":16777215,"Decimal":0,"Charset":"utf8","Collate":"utf8_bin","Elems":null},"state":5,"comment":""},{"id":22,"name":{"O":"tp_text","L":"tp_text"},"offset":21,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":252,"Flag":0,"Flen":65535,"Decimal":0,"Charset":"utf8","Collate":"utf8_bin","Elems":null},"state":5,"comment":""},{"id":23,"name":{"O":"tp_tinytext","L":"tp_tinytext"},"offset":22,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":249,"Flag":0,"Flen":255,"Decimal":0,"Charset":"utf8","Collate":"utf8_bin","Elems":null},"state":5,"comment":""},{"id":24,"name":{"O":"tp_bit","L":"tp_bit"},"offset":23,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":16,"Flag":32,"Flen":1,"Decimal":0,"Charset":"binary","Collate":"binary","Elems":null},"state":5,"comment":""}],"index_info":null,"fk_info":null,"state":5,"pk_is_handle":true,"comment":"","auto_inc_id":0,"max_col_id":24,"max_idx_id":0}

  at com.pingcap.tikv.catalog.CatalogTransaction.parseFromJson(CatalogTransaction.java:178)
  at com.pingcap.tikv.catalog.CatalogTransaction.getTables(CatalogTransaction.java:160)
  at com.pingcap.tikv.catalog.Catalog$CatalogCache.loadTables(Catalog.java:93)
  at com.pingcap.tikv.catalog.Catalog$CatalogCache.listTables(Catalog.java:79)
  at com.pingcap.tikv.catalog.Catalog.listTables(Catalog.java:141)
  at com.pingcap.tispark.MetaManager.getTables(MetaManager.scala:32)
  at org.apache.spark.sql.TiContext$$anonfun$tidbMapDatabase$1.apply(TiContext.scala:42)
  at org.apache.spark.sql.TiContext$$anonfun$tidbMapDatabase$1.apply(TiContext.scala:41)
  at scala.Option.foreach(Option.scala:257)
  at org.apache.spark.sql.TiContext.tidbMapDatabase(TiContext.scala:40)
  ... 48 elided
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Numeric value (4294967295) out of range of int
 at [Source: {"id":148,"name":{"O":"full_data_type_table","L":"full_data_type_table"},"charset":"","collate":"","cols":[{"id":1,"name":{"O":"id_dt","L":"id_dt"},"offset":0,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":3,"Flag":4227,"Flen":11,"Decimal":0,"Charset":"binary","Collate":"binary","Elems":null},"state":5,"comment":""},{"id":2,"name":{"O":"tp_varchar","L":"tp_varchar"},"offset":1,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":15,"Flag":0,"Flen":45,"Decimal":0,"Charset":"utf8","Collate":"utf8_bin","Elems":null},"state":5,"comment":""},{"id":3,"name":{"O":"tp_datetime","L":"tp_datetime"},"offset":2,"origin_default":null,"default":"CURRENT_TIMESTAMP","generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":12,"Flag":128,"Flen":19,"Decimal":0,"Charset":"binary","Collate":"binary","Elems":null},"state":5,"comment":""},{"id":4,"name":{"O":"tp_blob","L":"tp_blob"},"offset":3,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":252,"Flag":128,"Flen":65535,"Decimal":0,"Charset":"binary","Collate":"binary","Elems":null},"state":5,"comment":""},{"id":5,"name":{"O":"tp_binary","L":"tp_binary"},"offset":4,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":254,"Flag":128,"Flen":2,"Decimal":0,"Charset":"binary","Collate":"binary","Elems":null},"state":5,"comment":""},{"id":6,"name":{"O":"tp_date","L":"tp_date"},"offset":5,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":10,"Flag":128,"Flen":10,"Decimal":0,"Charset":"binary","Collate":"binary","Elems":null},"state":5,"comment":""},{"id":7,"name":{"O":"tp_timestamp","L":"tp_timestamp"},"offset":6,"origin_default":null,"default":"CURRENT_TIMESTAMP","generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":7,"Flag":1152,"Flen":19,"Decimal":0,"Charset":"binary","Collate":"binary","Elems":null},"state":5,"comment":""},{"id":8,"name":{"O":"tp_year","L":"tp_year"},"offset":7,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":13,"Flag":128,"Flen":4,"Decimal":0,"Charset":"binary","Collate":"binary","Elems":null},"state":5,"comment":""},{"id":9,"name":{"O":"tp_bigint","L":"tp_bigint"},"offset":8,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":8,"Flag":128,"Flen":20,"Decimal":0,"Charset":"binary","Collate":"binary","Elems":null},"state":5,"comment":""},{"id":10,"name":{"O":"tp_decimal","L":"tp_decimal"},"offset":9,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":246,"Flag":128,"Flen":11,"Decimal":0,"Charset":"binary","Collate":"binary","Elems":null},"state":5,"comment":""},{"id":11,"name":{"O":"tp_double","L":"tp_double"},"offset":10,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":5,"Flag":128,"Flen":22,"Decimal":-1,"Charset":"binary","Collate":"binary","Elems":null},"state":5,"comment":""},{"id":12,"name":{"O":"tp_float","L":"tp_float"},"offset":11,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":4,"Flag":128,"Flen":12,"Decimal":-1,"Charset":"binary","Collate":"binary","Elems":null},"state":5,"comment":""},{"id":13,"name":{"O":"tp_int","L":"tp_int"},"offset":12,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":3,"Flag":128,"Flen":11,"Decimal":0,"Charset":"binary","Collate":"binary","Elems":null},"state":5,"comment":""},{"id":14,"name":{"O":"tp_mediumint","L":"tp_mediumint"},"offset":13,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":9,"Flag":128,"Flen":9,"Decimal":0,"Charset":"binary","Collate":"binary","Elems":null},"state":5,"comment":""},{"id":15,"name":{"O":"tp_real","L":"tp_real"},"offset":14,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":5,"Flag":128,"Flen":22,"Decimal":-1,"Charset":"binary","Collate":"binary","Elems":null},"state":5,"comment":""},{"id":16,"name":{"O":"tp_smallint","L":"tp_smallint"},"offset":15,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":2,"Flag":128,"Flen":6,"Decimal":0,"Charset":"binary","Collate":"binary","Elems":null},"state":5,"comment":""},{"id":17,"name":{"O":"tp_tinyint","L":"tp_tinyint"},"offset":16,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":1,"Flag":128,"Flen":4,"Decimal":0,"Charset":"binary","Collate":"binary","Elems":null},"state":5,"comment":""},{"id":18,"name":{"O":"tp_char","L":"tp_char"},"offset":17,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":254,"Flag":0,"Flen":10,"Decimal":0,"Charset":"utf8","Collate":"utf8_bin","Elems":null},"state":5,"comment":""},{"id":19,"name":{"O":"tp_nvarchar","L":"tp_nvarchar"},"offset":18,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":15,"Flag":0,"Flen":40,"Decimal":0,"Charset":"utf8","Collate":"utf8_bin","Elems":null},"state":5,"comment":""},{"id":20,"name":{"O":"tp_longtext","L":"tp_longtext"},"offset":19,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":251,"Flag":0,"Flen":4294967295,"Decimal":0,"Charset":"utf8","Collate":"utf8_bin","Elems":null},"state":5,"comment":""},{"id":21,"name":{"O":"tp_mediumtext","L":"tp_mediumtext"},"offset":20,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":250,"Flag":0,"Flen":16777215,"Decimal":0,"Charset":"utf8","Collate":"utf8_bin","Elems":null},"state":5,"comment":""},{"id":22,"name":{"O":"tp_text","L":"tp_text"},"offset":21,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":252,"Flag":0,"Flen":65535,"Decimal":0,"Charset":"utf8","Collate":"utf8_bin","Elems":null},"state":5,"comment":""},{"id":23,"name":{"O":"tp_tinytext","L":"tp_tinytext"},"offset":22,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":249,"Flag":0,"Flen":255,"Decimal":0,"Charset":"utf8","Collate":"utf8_bin","Elems":null},"state":5,"comment":""},{"id":24,"name":{"O":"tp_bit","L":"tp_bit"},"offset":23,"origin_default":null,"default":null,"generated_expr_string":"","generated_stored":false,"dependences":null,"type":{"Tp":16,"Flag":32,"Flen":1,"Decimal":0,"Charset":"binary","Collate":"binary","Elems":null},"state":5,"comment":""}],"index_info":null,"fk_info":null,"state":5,"pk_is_handle":true,"comment":"","auto_inc_id":0,"max_col_id":24,"max_idx_id":0}; line: 1, column: 5926] (through reference chain: com.pingcap.tikv.meta.TiTableInfo["cols"]->java.util.ArrayList[19]->com.pingcap.tikv.meta.TiColumnInfo["type"]->com.pingcap.tikv.meta.InternalTypeHolder["Flen"])
  at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:210)
  at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:177)
  at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1474)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:465)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:378)
  at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1099)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:296)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
  at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:463)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:378)
  at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1099)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:296)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
  at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
  at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217)
  at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)
  at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:463)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:378)
  at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1099)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:296)
  at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
  at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3736)
  at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2726)
  at com.pingcap.tikv.catalog.CatalogTransaction.parseFromJson(CatalogTransaction.java:173)
  ... 57 more
```

```LongText```has an an attribute ```Flen``` of value ```4294967295```, which is beyond the upper bound of ```int```.

**Comment by Novemser** [comment]
It seems that there's an issue in the `protobuf` file we defined, in which we try to use an `int32` to represent `int64` data.

**Comment by Novemser** [comment]
Fixed.
