### ISSUE TITLE
Missing support for ENUM and SET type

### ISSUE THREAD

**Issue by Novemser** [pingcap/tispark#71]
Currently we don't support `ENUM` nor `SET` type in `TiSpark`, when running a query on columns with `ENUM` type or `SET` type, the following exception may be thrown:
```
com.pingcap.tikv.codec.InvalidCodecFormatException: Invalid Flag type for : 9
	at com.pingcap.tikv.types.BytesType.decodeNotNull(BytesType.java:49)
	at com.pingcap.tikv.types.DataType.decodeValueToRow(DataType.java:125)
	at com.pingcap.tikv.row.DefaultRowReader.readRow(DefaultRowReader.java:38)
	at com.pingcap.tikv.operation.DAGIterator.next(DAGIterator.java:103)
	at com.pingcap.tikv.operation.DAGIterator.next(DAGIterator.java:42)
	at com.pingcap.tispark.TiRDD$$anon$1.next(TiRDD.scala:72)
	at com.pingcap.tispark.TiRDD$$anon$1.next(TiRDD.scala:52)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:232)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:225)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:827)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:827)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by Novemser** [comment]
The SQL is `select * from user`, table `user` is in db `mysql`
