### ISSUE TITLE
`UnsupportedOperationException` when scanning

### ISSUE THREAD

**Issue by birdstorm** [pingcap/tispark#743]
```
com.pingcap.tikv.exception.TiClientInternalException: Error scanning data from region.

	at com.pingcap.tikv.operation.iterator.ScanIterator.loadCache(ScanIterator.java:94)

	at com.pingcap.tikv.operation.iterator.ScanIterator.hasNext(ScanIterator.java:105)

	at com.pingcap.tikv.catalog.CatalogTransaction.hashGetFields(CatalogTransaction.java:225)

	at com.pingcap.tikv.catalog.CatalogTransaction.getDatabases(CatalogTransaction.java:246)

	at com.pingcap.tikv.catalog.Catalog$CatalogCache.loadDatabases(Catalog.java:117)

	at com.pingcap.tikv.catalog.Catalog$CatalogCache.<init>(Catalog.java:60)

	at com.pingcap.tikv.catalog.Catalog$CatalogCache.<init>(Catalog.java:54)

	at com.pingcap.tikv.catalog.Catalog.reloadCache(Catalog.java:179)

	at com.pingcap.tikv.catalog.Catalog.lambda$new$0(Catalog.java:147)

	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

	at java.lang.Thread.run(Thread.java:748)

Caused by: java.lang.UnsupportedOperationException

	at java.util.Collections$UnmodifiableList.set(Collections.java:1311)

	at com.pingcap.tikv.region.RegionStoreClient.doScan(RegionStoreClient.java:295)

	at com.pingcap.tikv.region.RegionStoreClient.scan(RegionStoreClient.java:274)

	at com.pingcap.tikv.region.RegionStoreClient.scan(RegionStoreClient.java:335)

	at com.pingcap.tikv.operation.iterator.ScanIterator.loadCache(ScanIterator.java:73)

	... 15 more

```

**Comment by zhexuany** [comment]
closed by https://github.com/pingcap/tispark/pull/798
