### ISSUE TITLE
Caused by: shade.io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 570000000a

### ISSUE THREAD

**Issue by wangdabin1216** [pingcap/tispark#903]
I use 2.1.1-spark_2.4 to execute the following program.

val sparkConf = new SparkConf()
      .setIfMissing("spark.sql.extensions", "org.apache.spark.sql.TiExtensions")
      .setIfMissing("tidb.addr", "xxx")
      .setIfMissing("tidb.port", "4000")
      .setIfMissing("tidb.user", "xxx")
      .setIfMissing("tidb.password", "xxx")
      .setIfMissing("spark.tispark.pd.addresses", "xxx:2379")
    val spark = SparkSession.builder.config(sparkConf).getOrCreate()
    spark.sql("use tpch_test")
    spark.sql("select count(*) from lineitem").show

but get an error

2019/07/04 20:20:25 WARN  com.pingcap.tikv.PDClient:279 failed to get member from pd server.
shade.io.grpc.StatusRuntimeException: INTERNAL
	at shade.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:210)
	at shade.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:191)
	at shade.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:124)
	at org.tikv.kvproto.PDGrpc$PDBlockingStub.getMembers(PDGrpc.java:898)
	at com.pingcap.tikv.PDClient.getMembers(PDClient.java:272)
	at com.pingcap.tikv.PDClient.initCluster(PDClient.java:363)
	at com.pingcap.tikv.PDClient.createRaw(PDClient.java:395)
	at com.pingcap.tikv.TiSession.getPDClient(TiSession.java:80)
	at com.pingcap.tikv.TiSession.<init>(TiSession.java:49)
	at com.pingcap.tikv.TiSession.create(TiSession.java:153)
	at org.apache.spark.sql.TiContext.<init>(TiContext.scala:44)
	at org.apache.spark.sql.TiExtensions.getOrCreateTiContext(TiExtensions.scala:10)
	at org.apache.spark.sql.TiExtensions$$anonfun$apply$5.apply(TiExtensions.scala:18)
	at org.apache.spark.sql.TiExtensions$$anonfun$apply$5.apply(TiExtensions.scala:18)
	at org.apache.spark.sql.extensions.TiResolutionRule.<init>(rules.scala:31)
	at org.apache.spark.sql.TiExtensions$$anonfun$apply$6.apply(TiExtensions.scala:18)
	at org.apache.spark.sql.TiExtensions$$anonfun$apply$6.apply(TiExtensions.scala:18)
	at org.apache.spark.sql.SparkSessionExtensions$$anonfun$buildResolutionRules$1.apply(SparkSessionExtensions.scala:78)
	at org.apache.spark.sql.SparkSessionExtensions$$anonfun$buildResolutionRules$1.apply(SparkSessionExtensions.scala:78)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.spark.sql.SparkSessionExtensions.buildResolutionRules(SparkSessionExtensions.scala:78)
	at org.apache.spark.sql.internal.BaseSessionStateBuilder.customResolutionRules(BaseSessionStateBuilder.scala:183)
	at org.apache.spark.sql.internal.BaseSessionStateBuilder$$anon$1.<init>(BaseSessionStateBuilder.scala:161)
	at org.apache.spark.sql.internal.BaseSessionStateBuilder.analyzer(BaseSessionStateBuilder.scala:157)
	at org.apache.spark.sql.internal.BaseSessionStateBuilder$$anonfun$build$2.apply(BaseSessionStateBuilder.scala:293)
	at org.apache.spark.sql.internal.BaseSessionStateBuilder$$anonfun$build$2.apply(BaseSessionStateBuilder.scala:293)
	at org.apache.spark.sql.internal.SessionState.analyzer$lzycompute(SessionState.scala:79)
	at org.apache.spark.sql.internal.SessionState.analyzer(SessionState.scala:79)
	at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:58)
	at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:56)
	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:48)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:78)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:642)
	at cn.com.yillion.SparkSqoop$.main(SparkSqoop.scala:24)
	at cn.com.yillion.SparkSqoop.main(SparkSqoop.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: shade.io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 570000000a
	at shade.io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85)
	at shade.io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.verifyFirstFrameIsSettings(Http2ConnectionHandler.java:350)
	at shade.io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:251)
	at shade.io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:443)
	at shade.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at shade.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at shade.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at shade.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at shade.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at shade.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at shade.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at shade.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at shade.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at shade.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at shade.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at shade.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at shade.io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "main" java.lang.NullPointerException: Failed to init client for PD cluster.
	at shade.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:228)
	at com.pingcap.tikv.PDClient.initCluster(PDClient.java:368)
	at com.pingcap.tikv.PDClient.createRaw(PDClient.java:395)
	at com.pingcap.tikv.TiSession.getPDClient(TiSession.java:80)
	at com.pingcap.tikv.TiSession.<init>(TiSession.java:49)
	at com.pingcap.tikv.TiSession.create(TiSession.java:153)
	at org.apache.spark.sql.TiContext.<init>(TiContext.scala:44)
	at org.apache.spark.sql.TiExtensions.getOrCreateTiContext(TiExtensions.scala:10)
	at org.apache.spark.sql.TiExtensions$$anonfun$apply$5.apply(TiExtensions.scala:18)
	at org.apache.spark.sql.TiExtensions$$anonfun$apply$5.apply(TiExtensions.scala:18)
	at org.apache.spark.sql.extensions.TiResolutionRule.<init>(rules.scala:31)
	at org.apache.spark.sql.TiExtensions$$anonfun$apply$6.apply(TiExtensions.scala:18)
	at org.apache.spark.sql.TiExtensions$$anonfun$apply$6.apply(TiExtensions.scala:18)
	at org.apache.spark.sql.SparkSessionExtensions$$anonfun$buildResolutionRules$1.apply(SparkSessionExtensions.scala:78)
	at org.apache.spark.sql.SparkSessionExtensions$$anonfun$buildResolutionRules$1.apply(SparkSessionExtensions.scala:78)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.spark.sql.SparkSessionExtensions.buildResolutionRules(SparkSessionExtensions.scala:78)
	at org.apache.spark.sql.internal.BaseSessionStateBuilder.customResolutionRules(BaseSessionStateBuilder.scala:183)
	at org.apache.spark.sql.internal.BaseSessionStateBuilder$$anon$1.<init>(BaseSessionStateBuilder.scala:161)
	at org.apache.spark.sql.internal.BaseSessionStateBuilder.analyzer(BaseSessionStateBuilder.scala:157)
	at org.apache.spark.sql.internal.BaseSessionStateBuilder$$anonfun$build$2.apply(BaseSessionStateBuilder.scala:293)
	at org.apache.spark.sql.internal.BaseSessionStateBuilder$$anonfun$build$2.apply(BaseSessionStateBuilder.scala:293)
	at org.apache.spark.sql.internal.SessionState.analyzer$lzycompute(SessionState.scala:79)
	at org.apache.spark.sql.internal.SessionState.analyzer(SessionState.scala:79)
	at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:58)
	at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:56)
	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:48)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:78)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:642)
	at cn.com.yillion.SparkSqoop$.main(SparkSqoop.scala:24)
	at cn.com.yillion.SparkSqoop.main(SparkSqoop.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

why?
thx

**Comment by birdstorm** [comment]
> WARN com.pingcap.tikv.PDClient:279 failed to get member from pd server.
> Exception in thread "main" java.lang.NullPointerException: Failed to init client for PD cluster.

Hi, @wangdabin1216 

From the above lines we can conclude that the setting for pd addresses is incorrect. Please confirm that the pd address is available and connectable from Spark’s worker. Also, if you have multiple pd s, the addresses should be separated with comma. e.g., `192.168.0.1:2379,192.168.0.2:2379,192.168.0.3:2379`

**Comment by birdstorm** [comment]
@wangdabin1216 If problem still exists, please provide us with PD’s version so that we can reproduce the issue.

**Comment by wangdabin1216** [comment]
thx,
