### ISSUE TITLE
(equation/inequation with null) in where clause fails

### ISSUE THREAD

**Issue by birdstorm** [pingcap/tispark#98]
Problem occurs when we have some equation concerning null types

e.g.,
```
select x from a where x = null;
```
where `x` is of any type

Following exceptions are thrown:
```
ResultStage 84 (collect at SparkWrapper.scala:53) failed in 0.022 s due to Job aborted due to stage failure: Task 0 in stage 84.0 failed 1 times, most recent failure: Lost task 0.0 in stage 84.0 (TID 84, localhost, executor driver): com.pingcap.tikv.expression.TiExpressionException: NULL constant has no type
	at com.pingcap.tikv.expression.TiConstant.getType(TiConstant.java:90)
	at com.pingcap.tikv.expression.scalar.And.validateArguments(And.java:52)
	at com.pingcap.tikv.expression.TiFunctionExpression.<init>(TiFunctionExpression.java:34)
	at com.pingcap.tikv.expression.TiBinaryFunctionExpression.<init>(TiBinaryFunctionExpression.java:23)
	at com.pingcap.tikv.expression.scalar.And.<init>(And.java:28)
	at com.pingcap.tikv.predicates.PredicateUtils.mergeCNFExpressions(PredicateUtils.java:34)
	at com.pingcap.tikv.meta.TiSelectRequest.buildTableScan(TiSelectRequest.java:160)
	at com.pingcap.tikv.meta.TiSelectRequest.buildScan(TiSelectRequest.java:90)
	at com.pingcap.tikv.operation.SelectIterator.getRowIterator(SelectIterator.java:61)
	at com.pingcap.tikv.Snapshot.tableRead(Snapshot.java:115)
	at org.apache.spark.sql.tispark.TiRDD$$anon$2.<init>(TiRDD.scala:61)
	at org.apache.spark.sql.tispark.TiRDD.compute(TiRDD.scala:53)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
17/11/29 20:42:23 INFO DAGScheduler: Job 84 failed: collect at SparkWrapper.scala:53, took 0.026328 s
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 84.0 failed 1 times, most recent failure: Lost task 0.0 in stage 84.0 (TID 84, localhost, executor driver): com.pingcap.tikv.expression.TiExpressionException: NULL constant has no type
	at com.pingcap.tikv.expression.TiConstant.getType(TiConstant.java:90)
	at com.pingcap.tikv.expression.scalar.And.validateArguments(And.java:52)
	at com.pingcap.tikv.expression.TiFunctionExpression.<init>(TiFunctionExpression.java:34)
	at com.pingcap.tikv.expression.TiBinaryFunctionExpression.<init>(TiBinaryFunctionExpression.java:23)
	at com.pingcap.tikv.expression.scalar.And.<init>(And.java:28)
	at com.pingcap.tikv.predicates.PredicateUtils.mergeCNFExpressions(PredicateUtils.java:34)
	at com.pingcap.tikv.meta.TiSelectRequest.buildTableScan(TiSelectRequest.java:160)
	at com.pingcap.tikv.meta.TiSelectRequest.buildScan(TiSelectRequest.java:90)
	at com.pingcap.tikv.operation.SelectIterator.getRowIterator(SelectIterator.java:61)
	at com.pingcap.tikv.Snapshot.tableRead(Snapshot.java:115)
	at org.apache.spark.sql.tispark.TiRDD$$anon$2.<init>(TiRDD.scala:61)
	at org.apache.spark.sql.tispark.TiRDD.compute(TiRDD.scala:53)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1435)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1423)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1422)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1422)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:802)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1650)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1605)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1594)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:628)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1918)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1931)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1944)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1958)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:935)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:934)
	at org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:275)
	at org.apache.spark.sql.Dataset$$anonfun$org$apache$spark$sql$Dataset$$execute$1$1.apply(Dataset.scala:2371)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:57)
	at org.apache.spark.sql.Dataset.withNewExecutionId(Dataset.scala:2765)
	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$execute$1(Dataset.scala:2370)
	at org.apache.spark.sql.Dataset$$anonfun$org$apache$spark$sql$Dataset$$collect$1.apply(Dataset.scala:2375)
	at org.apache.spark.sql.Dataset$$anonfun$org$apache$spark$sql$Dataset$$collect$1.apply(Dataset.scala:2375)
	at org.apache.spark.sql.Dataset.withCallback(Dataset.scala:2778)
	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$collect(Dataset.scala:2375)
	at org.apache.spark.sql.Dataset.collect(Dataset.scala:2351)
	at com.pingcap.spark.SparkWrapper.querySpark(SparkWrapper.scala:53)
	at com.pingcap.spark.TestCase$$anonfun$2.apply(TestCase.scala:190)
	at com.pingcap.spark.TestCase$$anonfun$2.apply(TestCase.scala:190)
	at com.pingcap.spark.Utils$.time(Utils.scala:74)
	at com.pingcap.spark.TestCase.execSpark(TestCase.scala:191)
	at com.pingcap.spark.TestCase.execBothAndJudge(TestCase.scala:253)
	at com.pingcap.spark.TestNull.testConditions(TestNull.scala:47)
	at com.pingcap.spark.TestNull.run(TestNull.scala:64)
	at com.pingcap.spark.TestCase.testAndCalc(TestCase.scala:290)
	at com.pingcap.spark.TestCase.testInline(TestCase.scala:303)
	at com.pingcap.spark.TestCase.test(TestCase.scala:311)
	at com.pingcap.spark.TestCase.work(TestCase.scala:138)
	at com.pingcap.spark.TestCase$$anonfun$work$6.apply(TestCase.scala:142)
	at com.pingcap.spark.TestCase$$anonfun$work$6.apply(TestCase.scala:141)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at com.pingcap.spark.TestCase.work(TestCase.scala:141)
	at com.pingcap.spark.TestCase.init(TestCase.scala:75)
	at com.pingcap.spark.TestFramework$.main(TestFramework.scala:30)
	at com.pingcap.spark.TestFramework.main(TestFramework.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:738)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: com.pingcap.tikv.expression.TiExpressionException: NULL constant has no type
	at com.pingcap.tikv.expression.TiConstant.getType(TiConstant.java:90)
	at com.pingcap.tikv.expression.scalar.And.validateArguments(And.java:52)
	at com.pingcap.tikv.expression.TiFunctionExpression.<init>(TiFunctionExpression.java:34)
	at com.pingcap.tikv.expression.TiBinaryFunctionExpression.<init>(TiBinaryFunctionExpression.java:23)
	at com.pingcap.tikv.expression.scalar.And.<init>(And.java:28)
	at com.pingcap.tikv.predicates.PredicateUtils.mergeCNFExpressions(PredicateUtils.java:34)
	at com.pingcap.tikv.meta.TiSelectRequest.buildTableScan(TiSelectRequest.java:160)
	at com.pingcap.tikv.meta.TiSelectRequest.buildScan(TiSelectRequest.java:90)
	at com.pingcap.tikv.operation.SelectIterator.getRowIterator(SelectIterator.java:61)
	at com.pingcap.tikv.Snapshot.tableRead(Snapshot.java:115)
	at org.apache.spark.sql.tispark.TiRDD$$anon$2.<init>(TiRDD.scala:61)
	at org.apache.spark.sql.tispark.TiRDD.compute(TiRDD.scala:53)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Novemser** [comment]
Should be fixed in [#tispark#101](https://github.com/pingcap/tispark/pull/101)
